"""
数据库初始化和操作
"""
import json
from datetime import datetime
from pathlib import Path
from sqlalchemy import create_engine, text
from sqlalchemy.orm import sessionmaker, Session
from models import Base, User, UserProfile, WordLibrary, LearningSession, DailyRecord

DATABASE_URL = "sqlite:////app/data/wordlearn.db"

engine = create_engine(DATABASE_URL, connect_args={"check_same_thread": False})
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)


def init_db():
    """初始化数据库并导入系统词库"""
    Base.metadata.create_all(bind=engine)
    
    db = SessionLocal()
    try:
        # 数据库迁移：将 familiarity 列从 Integer 改为 Float
        try:
            db.execute(text("ALTER TABLE wrong_questions RENAME COLUMN familiarity TO familiarity_old"))
            db.execute(text("ALTER TABLE wrong_questions ADD COLUMN familiarity REAL DEFAULT 1.0"))
            db.execute(text("UPDATE wrong_questions SET familiarity = CAST(familiarity_old AS REAL)"))
            db.execute(text("ALTER TABLE wrong_questions DROP COLUMN familiarity_old"))
            db.commit()
            print("数据库迁移完成：familiarity 列已从 Integer 改为 Float")
        except Exception:
            db.rollback()
            # 列可能已经是 Float 了，忽略错误

        # 数据库迁移：为 users 表添加 phone 和 email 列
        try:
            db.execute(text("ALTER TABLE users ADD COLUMN phone VARCHAR"))
            db.execute(text("ALTER TABLE users ADD COLUMN email VARCHAR"))
            db.execute(text("CREATE UNIQUE INDEX IF NOT EXISTS ix_users_phone ON users (phone) WHERE phone IS NOT NULL"))
            db.execute(text("CREATE UNIQUE INDEX IF NOT EXISTS ix_users_email ON users (email) WHERE email IS NOT NULL"))
            db.commit()
            print("数据库迁移完成：users 表已添加 phone 和 email 列")
        except Exception:
            db.rollback()
        
        # 数据库迁移：为 user_profiles 表添加 continuous_signin_days 列
        try:
            db.execute(text("ALTER TABLE user_profiles ADD COLUMN continuous_signin_days INTEGER DEFAULT 0"))
            db.commit()
            print("数据库迁移完成：user_profiles 表已添加 continuous_signin_days 列")
        except Exception:
            db.rollback()
        
        # 检查是否已有数据，增量导入缺失的系统词库
        system_libraries = get_system_libraries()
        for lib_data in system_libraries:
            existing_lib = db.query(WordLibrary).filter(WordLibrary.id == lib_data["id"]).first()
            if existing_lib:
                continue
            lib = WordLibrary(
                id=lib_data["id"],
                name=lib_data["name"],
                type="system",
                grade=lib_data.get("grade"),
                description=lib_data.get("description"),
                words=json.dumps(lib_data["words"], ensure_ascii=False),
                created_at=lib_data["created_at"]
            )
            db.add(lib)
        
        db.commit()
        print("数据库初始化完成，系统词库已导入")
    finally:
        db.close()


def get_db() -> Session:
    """获取数据库会话"""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


def get_system_libraries():
    """系统词库数据"""
    return [
        {
            "id": "sys-shanghai-6",
            "name": "上海版六年级上册",
            "grade": "小学",
            "description": "上海版小学六年级上册英语词汇",
            "created_at": "2024-01-01",
            "words": [
                {"id": "sh6-1", "word": "classroom", "phonetic": "/ˈklɑːsruːm/", "meaning": "教室"},
                {"id": "sh6-2", "word": "blackboard", "phonetic": "/ˈblækbɔːrd/", "meaning": "黑板"},
                {"id": "sh6-3", "word": "window", "phonetic": "/ˈwɪndəʊ/", "meaning": "窗户"},
                {"id": "sh6-4", "word": "door", "phonetic": "/dɔːr/", "meaning": "门"},
                {"id": "sh6-5", "word": "floor", "phonetic": "/flɔːr/", "meaning": "地板"},
                {"id": "sh6-6", "word": "wall", "phonetic": "/wɔːl/", "meaning": "墙"},
                {"id": "sh6-7", "word": "ceiling", "phonetic": "/ˈsiːlɪŋ/", "meaning": "天花板"},
                {"id": "sh6-8", "word": "light", "phonetic": "/laɪt/", "meaning": "灯"},
                {"id": "sh6-9", "word": "fan", "phonetic": "/fæn/", "meaning": "风扇"},
                {"id": "sh6-10", "word": "computer", "phonetic": "/kəmˈpjuːtər/", "meaning": "电脑"},
                {"id": "sh6-11", "word": "keyboard", "phonetic": "/ˈkiːbɔːrd/", "meaning": "键盘"},
                {"id": "sh6-12", "word": "mouse", "phonetic": "/maʊs/", "meaning": "鼠标"},
                {"id": "sh6-13", "word": "screen", "phonetic": "/skriːn/", "meaning": "屏幕"},
                {"id": "sh6-14", "word": "printer", "phonetic": "/ˈprɪntər/", "meaning": "打印机"},
                {"id": "sh6-15", "word": "telephone", "phonetic": "/ˈtelɪfəʊn/", "meaning": "电话"},
                {"id": "sh6-16", "word": "mobile phone", "phonetic": "/ˈməʊbaɪl fəʊn/", "meaning": "手机"},
                {"id": "sh6-17", "word": "camera", "phonetic": "/ˈkæmərə/", "meaning": "照相机"},
                {"id": "sh6-18", "word": "television", "phonetic": "/ˈtelɪvɪʒn/", "meaning": "电视"},
                {"id": "sh6-19", "word": "radio", "phonetic": "/ˈreɪdiəʊ/", "meaning": "收音机"},
                {"id": "sh6-20", "word": "headphones", "phonetic": "/ˈhedfəʊnz/", "meaning": "耳机"},
                {"id": "sh6-21", "word": "speaker", "phonetic": "/ˈspiːkər/", "meaning": "扬声器"},
                {"id": "sh6-22", "word": "microphone", "phonetic": "/ˈmaɪkrəfəʊn/", "meaning": "麦克风"},
                {"id": "sh6-23", "word": "video", "phonetic": "/ˈvɪdiəʊ/", "meaning": "视频"},
                {"id": "sh6-24", "word": "movie", "phonetic": "/ˈmuːvi/", "meaning": "电影"},
                {"id": "sh6-25", "word": "music", "phonetic": "/ˈmjuːzɪk/", "meaning": "音乐"},
                {"id": "sh6-26", "word": "song", "phonetic": "/sɒŋ/", "meaning": "歌曲"},
                {"id": "sh6-27", "word": "dance", "phonetic": "/dɑːns/", "meaning": "舞蹈"},
                {"id": "sh6-28", "word": "game", "phonetic": "/ɡeɪm/", "meaning": "游戏"},
                {"id": "sh6-29", "word": "sport", "phonetic": "/spɔːrt/", "meaning": "运动"},
                {"id": "sh6-30", "word": "football", "phonetic": "/ˈfʊtbɔːl/", "meaning": "足球"},
                {"id": "sh6-31", "word": "basketball", "phonetic": "/ˈbɑːskɪtbɔːl/", "meaning": "篮球"},
                {"id": "sh6-32", "word": "volleyball", "phonetic": "/ˈvɒlibɔːl/", "meaning": "排球"},
                {"id": "sh6-33", "word": "tennis", "phonetic": "/ˈtenɪs/", "meaning": "网球"},
                {"id": "sh6-34", "word": "badminton", "phonetic": "/ˈbædmɪntən/", "meaning": "羽毛球"},
                {"id": "sh6-35", "word": "swimming", "phonetic": "/ˈswɪmɪŋ/", "meaning": "游泳"},
                {"id": "sh6-36", "word": "running", "phonetic": "/ˈrʌnɪŋ/", "meaning": "跑步"},
                {"id": "sh6-37", "word": "walking", "phonetic": "/ˈwɔːkɪŋ/", "meaning": "散步"},
                {"id": "sh6-38", "word": "cycling", "phonetic": "/ˈsaɪklɪŋ/", "meaning": "骑自行车"},
                {"id": "sh6-39", "word": "skating", "phonetic": "/ˈskeɪtɪŋ/", "meaning": "滑冰"},
                {"id": "sh6-40", "word": "skiing", "phonetic": "/ˈskiːɪŋ/", "meaning": "滑雪"},
                {"id": "sh6-41", "word": "climbing", "phonetic": "/ˈklaɪmɪŋ/", "meaning": "爬山"},
                {"id": "sh6-42", "word": "hiking", "phonetic": "/ˈhaɪkɪŋ/", "meaning": "远足"},
                {"id": "sh6-43", "word": "camping", "phonetic": "/ˈkæmpɪŋ/", "meaning": "露营"},
                {"id": "sh6-44", "word": "picnic", "phonetic": "/ˈpɪknɪk/", "meaning": "野餐"},
                {"id": "sh6-45", "word": "travel", "phonetic": "/ˈtrævl/", "meaning": "旅行"},
                {"id": "sh6-46", "word": "holiday", "phonetic": "/ˈhɒlədeɪ/", "meaning": "假日"},
                {"id": "sh6-47", "word": "vacation", "phonetic": "/vəˈkeɪʃn/", "meaning": "假期"},
                {"id": "sh6-48", "word": "weekend", "phonetic": "/ˌwiːkˈend/", "meaning": "周末"},
                {"id": "sh6-49", "word": "morning", "phonetic": "/ˈmɔːrnɪŋ/", "meaning": "早上"},
                {"id": "sh6-50", "word": "afternoon", "phonetic": "/ˌɑːftərˈnuːn/", "meaning": "下午"},
                {"id": "sh6-51", "word": "evening", "phonetic": "/ˈiːvnɪŋ/", "meaning": "晚上"},
                {"id": "sh6-52", "word": "night", "phonetic": "/naɪt/", "meaning": "夜晚"},
                {"id": "sh6-53", "word": "today", "phonetic": "/təˈdeɪ/", "meaning": "今天"},
                {"id": "sh6-54", "word": "tomorrow", "phonetic": "/təˈmɒrəʊ/", "meaning": "明天"},
                {"id": "sh6-55", "word": "yesterday", "phonetic": "/ˈjestərdeɪ/", "meaning": "昨天"},
                {"id": "sh6-56", "word": "week", "phonetic": "/wiːk/", "meaning": "周"},
                {"id": "sh6-57", "word": "month", "phonetic": "/mʌnθ/", "meaning": "月"},
                {"id": "sh6-58", "word": "year", "phonetic": "/jɪər/", "meaning": "年"},
                {"id": "sh6-59", "word": "season", "phonetic": "/ˈsiːzn/", "meaning": "季节"},
                {"id": "sh6-60", "word": "spring", "phonetic": "/sprɪŋ/", "meaning": "春天"},
                {"id": "sh6-61", "word": "summer", "phonetic": "/ˈsʌmər/", "meaning": "夏天"},
                {"id": "sh6-62", "word": "autumn", "phonetic": "/ˈɔːtəm/", "meaning": "秋天"},
                {"id": "sh6-63", "word": "winter", "phonetic": "/ˈwɪntər/", "meaning": "冬天"},
                {"id": "sh6-64", "word": "weather", "phonetic": "/ˈweðər/", "meaning": "天气"},
                {"id": "sh6-65", "word": "sunny", "phonetic": "/ˈsʌni/", "meaning": "晴朗的"},
                {"id": "sh6-66", "word": "rainy", "phonetic": "/ˈreɪni/", "meaning": "下雨的"},
                {"id": "sh6-67", "word": "cloudy", "phonetic": "/ˈklaʊdi/", "meaning": "多云的"},
                {"id": "sh6-68", "word": "snowy", "phonetic": "/ˈsnəʊi/", "meaning": "下雪的"},
                {"id": "sh6-69", "word": "windy", "phonetic": "/ˈwɪndi/", "meaning": "有风的"},
                {"id": "sh6-70", "word": "cold", "phonetic": "/kəʊld/", "meaning": "冷的"},
                {"id": "sh6-71", "word": "warm", "phonetic": "/wɔːrm/", "meaning": "温暖的"},
                {"id": "sh6-72", "word": "hot", "phonetic": "/hɒt/", "meaning": "热的"},
                {"id": "sh6-73", "word": "cool", "phonetic": "/kuːl/", "meaning": "凉爽的"},
                {"id": "sh6-74", "word": "temperature", "phonetic": "/ˈtemprətʃər/", "meaning": "温度"},
                {"id": "sh6-75", "word": "degree", "phonetic": "/dɪˈɡriː/", "meaning": "度"},
                {"id": "sh6-76", "word": "rain", "phonetic": "/reɪn/", "meaning": "雨"},
                {"id": "sh6-77", "word": "snow", "phonetic": "/snəʊ/", "meaning": "雪"},
                {"id": "sh6-78", "word": "wind", "phonetic": "/wɪnd/", "meaning": "风"},
                {"id": "sh6-79", "word": "cloud", "phonetic": "/klaʊd/", "meaning": "云"},
                {"id": "sh6-80", "word": "sky", "phonetic": "/skaɪ/", "meaning": "天空"},
            ],
        },
        {
            "id": "sys-primary-1",
            "name": "小学一年级",
            "grade": "小学",
            "description": "人教版小学一年级英语核心词汇",
            "created_at": "2024-01-01",
            "words": [
                {"id": "p1-1", "word": "apple", "phonetic": "/ˈæpəl/", "meaning": "苹果"},
                {"id": "p1-2", "word": "ball", "phonetic": "/bɔːl/", "meaning": "球"},
                {"id": "p1-3", "word": "cat", "phonetic": "/kæt/", "meaning": "猫"},
                {"id": "p1-4", "word": "dog", "phonetic": "/dɒɡ/", "meaning": "狗"},
                {"id": "p1-5", "word": "egg", "phonetic": "/eɡ/", "meaning": "蛋"},
                {"id": "p1-6", "word": "fish", "phonetic": "/fɪʃ/", "meaning": "鱼"},
                {"id": "p1-7", "word": "girl", "phonetic": "/ɡɜːl/", "meaning": "女孩"},
                {"id": "p1-8", "word": "hat", "phonetic": "/hæt/", "meaning": "帽子"},
                {"id": "p1-9", "word": "ice", "phonetic": "/aɪs/", "meaning": "冰"},
                {"id": "p1-10", "word": "juice", "phonetic": "/dʒuːs/", "meaning": "果汁"},
                {"id": "p1-11", "word": "kite", "phonetic": "/kaɪt/", "meaning": "风筝"},
                {"id": "p1-12", "word": "lion", "phonetic": "/ˈlaɪən/", "meaning": "狮子"},
                {"id": "p1-13", "word": "milk", "phonetic": "/mɪlk/", "meaning": "牛奶"},
                {"id": "p1-14", "word": "nose", "phonetic": "/nəʊz/", "meaning": "鼻子"},
                {"id": "p1-15", "word": "orange", "phonetic": "/ˈɒrɪndʒ/", "meaning": "橙子"},
                {"id": "p1-16", "word": "pen", "phonetic": "/pen/", "meaning": "钢笔"},
                {"id": "p1-17", "word": "queen", "phonetic": "/kwiːn/", "meaning": "女王"},
                {"id": "p1-18", "word": "red", "phonetic": "/red/", "meaning": "红色的"},
                {"id": "p1-19", "word": "sun", "phonetic": "/sʌn/", "meaning": "太阳"},
                {"id": "p1-20", "word": "tree", "phonetic": "/triː/", "meaning": "树"},
            ],
        },
        {
            "id": "sys-primary-3",
            "name": "小学三年级",
            "grade": "小学",
            "description": "人教版小学三年级英语词汇",
            "created_at": "2024-01-01",
            "words": [
                {"id": "p3-1", "word": "book", "phonetic": "/bʊk/", "meaning": "书"},
                {"id": "p3-2", "word": "bag", "phonetic": "/bæɡ/", "meaning": "包；书包"},
                {"id": "p3-3", "word": "ruler", "phonetic": "/ˈruːlər/", "meaning": "尺子"},
                {"id": "p3-4", "word": "pencil", "phonetic": "/ˈpensl/", "meaning": "铅笔"},
                {"id": "p3-5", "word": "eraser", "phonetic": "/ɪˈreɪzər/", "meaning": "橡皮擦"},
                {"id": "p3-6", "word": "school", "phonetic": "/skuːl/", "meaning": "学校"},
                {"id": "p3-7", "word": "teacher", "phonetic": "/ˈtiːtʃər/", "meaning": "教师"},
                {"id": "p3-8", "word": "student", "phonetic": "/ˈstjuːdnt/", "meaning": "学生"},
                {"id": "p3-9", "word": "desk", "phonetic": "/desk/", "meaning": "桌子"},
                {"id": "p3-10", "word": "chair", "phonetic": "/tʃeər/", "meaning": "椅子"},
                {"id": "p3-11", "word": "yellow", "phonetic": "/ˈjeləʊ/", "meaning": "黄色的"},
                {"id": "p3-12", "word": "blue", "phonetic": "/bluː/", "meaning": "蓝色的"},
                {"id": "p3-13", "word": "green", "phonetic": "/ɡriːn/", "meaning": "绿色的"},
                {"id": "p3-14", "word": "white", "phonetic": "/waɪt/", "meaning": "白色的"},
                {"id": "p3-15", "word": "black", "phonetic": "/blæk/", "meaning": "黑色的"},
                {"id": "p3-16", "word": "father", "phonetic": "/ˈfɑːðər/", "meaning": "父亲"},
                {"id": "p3-17", "word": "mother", "phonetic": "/ˈmʌðər/", "meaning": "母亲"},
                {"id": "p3-18", "word": "brother", "phonetic": "/ˈbrʌðər/", "meaning": "兄弟"},
                {"id": "p3-19", "word": "sister", "phonetic": "/ˈsɪstər/", "meaning": "姐妹"},
                {"id": "p3-20", "word": "friend", "phonetic": "/frend/", "meaning": "朋友"},
                {"id": "p3-21", "word": "happy", "phonetic": "/ˈhæpi/", "meaning": "快乐的"},
                {"id": "p3-22", "word": "good", "phonetic": "/ɡʊd/", "meaning": "好的"},
                {"id": "p3-23", "word": "big", "phonetic": "/bɪɡ/", "meaning": "大的"},
                {"id": "p3-24", "word": "small", "phonetic": "/smɔːl/", "meaning": "小的"},
                {"id": "p3-25", "word": "hot", "phonetic": "/hɒt/", "meaning": "热的"},
            ],
        },
        {
            "id": "sys-primary-5",
            "name": "小学五年级",
            "grade": "小学",
            "description": "人教版小学五年级英语词汇",
            "created_at": "2024-01-01",
            "words": [
                {"id": "p5-1", "word": "Monday", "phonetic": "/ˈmʌndeɪ/", "meaning": "星期一"},
                {"id": "p5-2", "word": "Tuesday", "phonetic": "/ˈtjuːzdeɪ/", "meaning": "星期二"},
                {"id": "p5-3", "word": "Wednesday", "phonetic": "/ˈwenzdeɪ/", "meaning": "星期三"},
                {"id": "p5-4", "word": "Thursday", "phonetic": "/ˈθɜːzdeɪ/", "meaning": "星期四"},
                {"id": "p5-5", "word": "Friday", "phonetic": "/ˈfraɪdeɪ/", "meaning": "星期五"},
                {"id": "p5-6", "word": "Saturday", "phonetic": "/ˈsætədeɪ/", "meaning": "星期六"},
                {"id": "p5-7", "word": "Sunday", "phonetic": "/ˈsʌndeɪ/", "meaning": "星期日"},
                {"id": "p5-8", "word": "January", "phonetic": "/ˈdʒænjueri/", "meaning": "一月"},
                {"id": "p5-9", "word": "February", "phonetic": "/ˈfebrueri/", "meaning": "二月"},
                {"id": "p5-10", "word": "March", "phonetic": "/mɑːtʃ/", "meaning": "三月"},
                {"id": "p5-11", "word": "April", "phonetic": "/ˈeɪprəl/", "meaning": "四月"},
                {"id": "p5-12", "word": "sports", "phonetic": "/spɔːts/", "meaning": "运动"},
                {"id": "p5-13", "word": "swimming", "phonetic": "/ˈswɪmɪŋ/", "meaning": "游泳"},
                {"id": "p5-14", "word": "running", "phonetic": "/ˈrʌnɪŋ/", "meaning": "跑步"},
                {"id": "p5-15", "word": "reading", "phonetic": "/ˈriːdɪŋ/", "meaning": "阅读"},
                {"id": "p5-16", "word": "shopping", "phonetic": "/ˈʃɒpɪŋ/", "meaning": "购物"},
                {"id": "p5-17", "word": "cooking", "phonetic": "/ˈkʊkɪŋ/", "meaning": "烹饪"},
                {"id": "p5-18", "word": "hospital", "phonetic": "/ˈhɒspɪtl/", "meaning": "医院"},
                {"id": "p5-19", "word": "library", "phonetic": "/ˈlaɪbrəri/", "meaning": "图书馆"},
                {"id": "p5-20", "word": "supermarket", "phonetic": "/ˈsuːpəmɑːkɪt/", "meaning": "超市"},
                {"id": "p5-21", "word": "turn left", "phonetic": "/tɜːn left/", "meaning": "向左转"},
                {"id": "p5-22", "word": "turn right", "phonetic": "/tɜːn raɪt/", "meaning": "向右转"},
                {"id": "p5-23", "word": "go straight", "phonetic": "/ɡəʊ streɪt/", "meaning": "直走"},
                {"id": "p5-24", "word": "take a bus", "phonetic": "/teɪk ə bʌs/", "meaning": "乘公共汽车"},
                {"id": "p5-25", "word": "by subway", "phonetic": "/baɪ ˈsʌbweɪ/", "meaning": "乘地铁"},
            ],
        },
        {
            "id": "sys-junior-7",
            "name": "初一（七年级）",
            "grade": "初中",
            "description": "人教版初一英语核心词汇",
            "created_at": "2024-01-01",
            "words": [
                {"id": "j7-1", "word": "family", "phonetic": "/ˈfæməli/", "meaning": "家庭；家人"},
                {"id": "j7-2", "word": "subject", "phonetic": "/ˈsʌbdʒɪkt/", "meaning": "学科；科目"},
                {"id": "j7-3", "word": "favorite", "phonetic": "/ˈfeɪvərɪt/", "meaning": "最喜欢的"},
                {"id": "j7-4", "word": "breakfast", "phonetic": "/ˈbrekfəst/", "meaning": "早餐"},
                {"id": "j7-5", "word": "lunch", "phonetic": "/lʌntʃ/", "meaning": "午餐"},
                {"id": "j7-6", "word": "dinner", "phonetic": "/ˈdɪnər/", "meaning": "晚餐"},
                {"id": "j7-7", "word": "bedroom", "phonetic": "/ˈbedrʊm/", "meaning": "卧室"},
                {"id": "j7-8", "word": "living room", "phonetic": "/ˈlɪvɪŋ ruːm/", "meaning": "客厅"},
                {"id": "j7-9", "word": "kitchen", "phonetic": "/ˈkɪtʃɪn/", "meaning": "厨房"},
                {"id": "j7-10", "word": "bathroom", "phonetic": "/ˈbɑːθruːm/", "meaning": "浴室；洗手间"},
                {"id": "j7-11", "word": "telephone", "phonetic": "/ˈtelɪfəʊn/", "meaning": "电话"},
                {"id": "j7-12", "word": "computer", "phonetic": "/kəmˈpjuːtər/", "meaning": "电脑"},
                {"id": "j7-13", "word": "television", "phonetic": "/ˈtelɪvɪʒn/", "meaning": "电视机"},
                {"id": "j7-14", "word": "interesting", "phonetic": "/ˈɪntrəstɪŋ/", "meaning": "有趣的"},
                {"id": "j7-15", "word": "difficult", "phonetic": "/ˈdɪfɪkəlt/", "meaning": "困难的"},
                {"id": "j7-16", "word": "easy", "phonetic": "/ˈiːzi/", "meaning": "容易的"},
                {"id": "j7-17", "word": "boring", "phonetic": "/ˈbɔːrɪŋ/", "meaning": "无聊的"},
                {"id": "j7-18", "word": "exciting", "phonetic": "/ɪkˈsaɪtɪŋ/", "meaning": "令人兴奋的"},
                {"id": "j7-19", "word": "relaxing", "phonetic": "/rɪˈlæksɪŋ/", "meaning": "轻松的"},
                {"id": "j7-20", "word": "dangerous", "phonetic": "/ˈdeɪndʒərəs/", "meaning": "危险的"},
                {"id": "j7-21", "word": "practice", "phonetic": "/ˈpræktɪs/", "meaning": "练习；实践"},
                {"id": "j7-22", "word": "remember", "phonetic": "/rɪˈmembər/", "meaning": "记得；记住"},
                {"id": "j7-23", "word": "forget", "phonetic": "/fəˈɡet/", "meaning": "忘记"},
                {"id": "j7-24", "word": "understand", "phonetic": "/ˌʌndəˈstænd/", "meaning": "理解；明白"},
                {"id": "j7-25", "word": "explain", "phonetic": "/ɪkˈspleɪn/", "meaning": "解释；说明"},
                {"id": "j7-26", "word": "music", "phonetic": "/ˈmjuːzɪk/", "meaning": "音乐"},
                {"id": "j7-27", "word": "science", "phonetic": "/ˈsaɪəns/", "meaning": "科学"},
                {"id": "j7-28", "word": "history", "phonetic": "/ˈhɪstri/", "meaning": "历史"},
                {"id": "j7-29", "word": "geography", "phonetic": "/dʒiˈɒɡrəfi/", "meaning": "地理"},
                {"id": "j7-30", "word": "biology", "phonetic": "/baɪˈɒlədʒi/", "meaning": "生物学"},
            ],
        },
        {
            "id": "sys-junior-9",
            "name": "初三（九年级）",
            "grade": "初中",
            "description": "人教版初三英语重点词汇",
            "created_at": "2024-01-01",
            "words": [
                {"id": "j9-1", "word": "achieve", "phonetic": "/əˈtʃiːv/", "meaning": "实现；取得"},
                {"id": "j9-2", "word": "attitude", "phonetic": "/ˈætɪtjuːd/", "meaning": "态度；看法"},
                {"id": "j9-3", "word": "challenge", "phonetic": "/ˈtʃælɪndʒ/", "meaning": "挑战"},
                {"id": "j9-4", "word": "confidence", "phonetic": "/ˈkɒnfɪdəns/", "meaning": "信心；自信"},
                {"id": "j9-5", "word": "creativity", "phonetic": "/ˌkriːeɪˈtɪvəti/", "meaning": "创造力"},
                {"id": "j9-6", "word": "develop", "phonetic": "/dɪˈveləp/", "meaning": "发展；开发"},
                {"id": "j9-7", "word": "education", "phonetic": "/ˌedʒuˈkeɪʃn/", "meaning": "教育"},
                {"id": "j9-8", "word": "encourage", "phonetic": "/ɪnˈkʌrɪdʒ/", "meaning": "鼓励"},
                {"id": "j9-9", "word": "environment", "phonetic": "/ɪnˈvaɪrənmənt/", "meaning": "环境"},
                {"id": "j9-10", "word": "experience", "phonetic": "/ɪkˈspɪəriəns/", "meaning": "经历；经验"},
                {"id": "j9-11", "word": "government", "phonetic": "/ˈɡʌvənmənt/", "meaning": "政府"},
                {"id": "j9-12", "word": "imagination", "phonetic": "/ɪˌmædʒɪˈneɪʃn/", "meaning": "想象力"},
                {"id": "j9-13", "word": "improve", "phonetic": "/ɪmˈpruːv/", "meaning": "改善；提高"},
                {"id": "j9-14", "word": "influence", "phonetic": "/ˈɪnfluəns/", "meaning": "影响"},
                {"id": "j9-15", "word": "knowledge", "phonetic": "/ˈnɒlɪdʒ/", "meaning": "知识；学问"},
                {"id": "j9-16", "word": "opportunity", "phonetic": "/ˌɒpəˈtjuːnəti/", "meaning": "机会；时机"},
                {"id": "j9-17", "word": "pollution", "phonetic": "/pəˈluːʃn/", "meaning": "污染"},
                {"id": "j9-18", "word": "population", "phonetic": "/ˌpɒpjuˈleɪʃn/", "meaning": "人口"},
                {"id": "j9-19", "word": "protect", "phonetic": "/prəˈtekt/", "meaning": "保护"},
                {"id": "j9-20", "word": "recycling", "phonetic": "/ˌriːˈsaɪklɪŋ/", "meaning": "回收利用"},
                {"id": "j9-21", "word": "responsibility", "phonetic": "/rɪˌspɒnsəˈbɪləti/", "meaning": "责任；职责"},
                {"id": "j9-22", "word": "scientific", "phonetic": "/ˌsaɪənˈtɪfɪk/", "meaning": "科学的"},
                {"id": "j9-23", "word": "succeed", "phonetic": "/səkˈsiːd/", "meaning": "成功"},
                {"id": "j9-24", "word": "technology", "phonetic": "/tekˈnɒlədʒi/", "meaning": "技术；科技"},
                {"id": "j9-25", "word": "volunteer", "phonetic": "/ˌvɒlənˈtɪər/", "meaning": "志愿者；自愿"},
            ],
        },
        {
            "id": "sys-high-10",
            "name": "高中必修词汇",
            "grade": "高中",
            "description": "高中英语课程标准必修词汇",
            "created_at": "2024-01-01",
            "words": [
                {"id": "h10-1", "word": "abandon", "phonetic": "/əˈbændən/", "meaning": "放弃；遗弃"},
                {"id": "h10-2", "word": "absence", "phonetic": "/ˈæbsəns/", "meaning": "缺席；不在场"},
                {"id": "h10-3", "word": "accomplish", "phonetic": "/əˈkɒmplɪʃ/", "meaning": "完成；实现"},
                {"id": "h10-4", "word": "accurate", "phonetic": "/ˈækjərət/", "meaning": "准确的；精确的"},
                {"id": "h10-5", "word": "adequate", "phonetic": "/ˈædɪkwət/", "meaning": "足够的；适当的"},
                {"id": "h10-6", "word": "admire", "phonetic": "/ədˈmaɪər/", "meaning": "钦佩；羡慕"},
                {"id": "h10-7", "word": "adventure", "phonetic": "/ədˈventʃər/", "meaning": "冒险；奇遇"},
                {"id": "h10-8", "word": "afford", "phonetic": "/əˈfɔːd/", "meaning": "负担得起；提供"},
                {"id": "h10-9", "word": "aggressive", "phonetic": "/əˈɡresɪv/", "meaning": "侵略性的；好斗的"},
                {"id": "h10-10", "word": "ambition", "phonetic": "/æmˈbɪʃn/", "meaning": "雄心；野心"},
                {"id": "h10-11", "word": "analyze", "phonetic": "/ˈænəlaɪz/", "meaning": "分析"},
                {"id": "h10-12", "word": "anxiety", "phonetic": "/æŋˈzaɪəti/", "meaning": "焦虑；担心"},
                {"id": "h10-13", "word": "appreciate", "phonetic": "/əˈpriːʃieɪt/", "meaning": "欣赏；感激"},
                {"id": "h10-14", "word": "appropriate", "phonetic": "/əˈprəʊpriət/", "meaning": "合适的；恰当的"},
                {"id": "h10-15", "word": "approximately", "phonetic": "/əˈprɒksɪmətli/", "meaning": "大约；近似地"},
                {"id": "h10-16", "word": "argument", "phonetic": "/ˈɑːɡjumənt/", "meaning": "争论；论点"},
                {"id": "h10-17", "word": "artificial", "phonetic": "/ˌɑːtɪˈfɪʃl/", "meaning": "人工的；人造的"},
                {"id": "h10-18", "word": "authority", "phonetic": "/ɔːˈθɒrəti/", "meaning": "权力；当局"},
                {"id": "h10-19", "word": "average", "phonetic": "/ˈævərɪdʒ/", "meaning": "平均的；普通的"},
                {"id": "h10-20", "word": "barely", "phonetic": "/ˈbeəli/", "meaning": "几乎不；刚刚"},
                {"id": "h10-21", "word": "beneficial", "phonetic": "/ˌbenɪˈfɪʃl/", "meaning": "有益的；有利的"},
                {"id": "h10-22", "word": "capability", "phonetic": "/ˌkeɪpəˈbɪləti/", "meaning": "能力；才能"},
                {"id": "h10-23", "word": "circumstances", "phonetic": "/ˈsɜːkəmstænsɪz/", "meaning": "情况；环境"},
                {"id": "h10-24", "word": "civilization", "phonetic": "/ˌsɪvəlaɪˈzeɪʃn/", "meaning": "文明；文明社会"},
                {"id": "h10-25", "word": "colleague", "phonetic": "/ˈkɒliːɡ/", "meaning": "同事；同僚"},
                {"id": "h10-26", "word": "commit", "phonetic": "/kəˈmɪt/", "meaning": "犯（罪）；承诺"},
                {"id": "h10-27", "word": "communicate", "phonetic": "/kəˈmjuːnɪkeɪt/", "meaning": "沟通；传达"},
                {"id": "h10-28", "word": "consequence", "phonetic": "/ˈkɒnsɪkwəns/", "meaning": "结果；后果"},
                {"id": "h10-29", "word": "considerable", "phonetic": "/kənˈsɪdərəbl/", "meaning": "相当大的；值得注意的"},
                {"id": "h10-30", "word": "contribute", "phonetic": "/kənˈtrɪbjuːt/", "meaning": "贡献；捐献"},
            ],
        },
        {
            "id": "sys-grade6-down-u1",
            "name": "六年级下册 Unit 1",
            "grade": "小学",
            "description": "上海版六年级下册 Unit 1 英语词汇",
            "created_at": "2024-01-01",
            "words": [
                {"id": "g6d1-1", "word": "different", "phonetic": "/ˈdɪfrənt/", "meaning": "不平常的；与众不同的；不同的；有区别的", "example_sentence": "Everyone is different and that makes the world interesting."},
                {"id": "g6d1-2", "word": "notice", "phonetic": "/ˈnəʊtɪs/", "meaning": "注意", "example_sentence": "Please notice the sign on the door before entering."},
                {"id": "g6d1-3", "word": "swan", "phonetic": "/swɒn/", "meaning": "天鹅", "example_sentence": "The beautiful swan swam across the lake gracefully."},
                {"id": "g6d1-4", "word": "partner", "phonetic": "/ˈpɑːtnə(r)/", "meaning": "搭档；同伴", "example_sentence": "I worked with my partner to finish the project on time."},
                {"id": "g6d1-5", "word": "slim", "phonetic": "/slɪm/", "meaning": "苗条的；纤细的", "example_sentence": "She is slim and healthy because she exercises every day."},
                {"id": "g6d1-6", "word": "fat", "phonetic": "/fæt/", "meaning": "肥的；胖的", "example_sentence": "The cat is so fat that it can barely move."},
                {"id": "g6d1-7", "word": "curly", "phonetic": "/ˈkɜːli/", "meaning": "卷曲状的", "example_sentence": "She has beautiful curly hair that bounces when she walks."},
                {"id": "g6d1-8", "word": "straight", "phonetic": "/streɪt/", "meaning": "直的", "example_sentence": "Draw a straight line from point A to point B."},
                {"id": "g6d1-9", "word": "T-shirt", "phonetic": "/ˈtiː ʃɜːt/", "meaning": "T恤衫；短袖汗衫", "example_sentence": "I usually wear a T-shirt and shorts in summer."},
                {"id": "g6d1-10", "word": "jeans", "phonetic": "/dʒiːnz/", "meaning": "牛仔裤", "example_sentence": "He wore his favorite jeans to school today."},
                {"id": "g6d1-11", "word": "size", "phonetic": "/saɪz/", "meaning": "大小；尺码", "example_sentence": "What size shoes do you wear?"},
                {"id": "g6d1-12", "word": "shape", "phonetic": "/ʃeɪp/", "meaning": "形状；外形", "example_sentence": "The cloud has an unusual shape today."},
                {"id": "g6d1-13", "word": "skin", "phonetic": "/skɪn/", "meaning": "皮肤", "example_sentence": "She has soft skin because she takes good care of it."},
                {"id": "g6d1-14", "word": "special", "phonetic": "/ˈspeʃl/", "meaning": "特殊的；特别的", "example_sentence": "Today is a special day because it is my birthday."},
                {"id": "g6d1-15", "word": "number", "phonetic": "/ˈnʌmbə(r)/", "meaning": "编号；数字；数量", "example_sentence": "What is your phone number?"},
                {"id": "g6d1-16", "word": "than", "phonetic": "/ðæn; ðən/", "meaning": "比", "example_sentence": "A basketball is bigger than a tennis ball."},
                {"id": "g6d1-17", "word": "fair", "phonetic": "/feə(r)/", "meaning": "（头发或皮肤）浅色的；白皙的", "example_sentence": "She has fair skin and blonde hair."},
                {"id": "g6d1-18", "word": "talent", "phonetic": "/ˈtælənt/", "meaning": "天才；天赋", "example_sentence": "She has a talent for playing the piano."},
                {"id": "g6d1-19", "word": "programme", "phonetic": "/ˈprəʊɡræm/", "meaning": "节目单；计划；方案；活动安排", "example_sentence": "What is your favourite TV programme?"},
                {"id": "g6d1-20", "word": "hall", "phonetic": "/hɔːl/", "meaning": "礼堂；大厅", "example_sentence": "The school hall is large enough for all the students."},
                {"id": "g6d1-21", "word": "butterfly", "phonetic": "/ˈbʌtəflaɪ/", "meaning": "蝴蝶", "example_sentence": "A beautiful butterfly landed on the flower."},
                {"id": "g6d1-22", "word": "violin", "phonetic": "/ˌvaɪəˈlɪn/", "meaning": "小提琴", "example_sentence": "She plays the violin in the school orchestra."},
                {"id": "g6d1-23", "word": "host", "phonetic": "/həʊst/", "meaning": "节目主持人", "example_sentence": "The host welcomed all the guests to the show."},
                {"id": "g6d1-24", "word": "sound", "phonetic": "/saʊnd/", "meaning": "听起来", "example_sentence": "That sounds like a great idea!"},
                {"id": "g6d1-25", "word": "exciting", "phonetic": "/ɪkˈsaɪtɪŋ/", "meaning": "令人兴奋的；令人激动的", "example_sentence": "The basketball game was so exciting to watch."},
                {"id": "g6d1-26", "word": "anything", "phonetic": "/ˈeniθɪŋ/", "meaning": "任何东西；任何事物", "example_sentence": "Is there anything I can do to help you?"},
                {"id": "g6d1-27", "word": "someone", "phonetic": "/ˈsʌmwʌn/", "meaning": "某人", "example_sentence": "Someone is knocking at the door."},
                {"id": "g6d1-28", "word": "drum", "phonetic": "/drʌm/", "meaning": "打鼓", "example_sentence": "He plays the drum in a rock band."},
                {"id": "g6d1-29", "word": "voice", "phonetic": "/vɔɪs/", "meaning": "嗓音；说话声；歌唱声", "example_sentence": "She has a beautiful singing voice."},
                {"id": "g6d1-30", "word": "person", "phonetic": "/ˈpɜːsn/", "meaning": "人；个人", "example_sentence": "He is a very kind person."},
                {"id": "g6d1-31", "word": "hobby", "phonetic": "/ˈhɒbi/", "meaning": "业余爱好", "example_sentence": "My hobby is collecting stamps from different countries."},
                {"id": "g6d1-32", "word": "personality", "phonetic": "/ˌpɜːsəˈnæləti/", "meaning": "性格；个性", "example_sentence": "She has a cheerful personality that everyone loves."},
                {"id": "g6d1-33", "word": "ability", "phonetic": "/əˈbɪləti/", "meaning": "才能；本领；能力", "example_sentence": "She has the ability to learn languages very quickly."},
                {"id": "g6d1-34", "word": "accept", "phonetic": "/əkˈsept/", "meaning": "接受；同意", "example_sentence": "Please accept this gift as a token of my appreciation."},
                {"id": "g6d1-35", "word": "wise", "phonetic": "/waɪz/", "meaning": "充满智慧的；明智的", "example_sentence": "It is wise to study hard for the exam."},
                {"id": "g6d1-36", "word": "without", "phonetic": "/wɪˈðaʊt/", "meaning": "没有；缺乏", "example_sentence": "I cannot live without my phone."},
                {"id": "g6d1-37", "word": "doubt", "phonetic": "/daʊt/", "meaning": "疑惑；疑问", "example_sentence": "I have no doubt that you will pass the test."},
                {"id": "g6d1-38", "word": "laugh", "phonetic": "/lɑːf/", "meaning": "笑；发笑", "example_sentence": "The joke made everyone laugh out loud."},
                {"id": "g6d1-39", "word": "laugh at", "phonetic": "", "meaning": "嘲笑", "example_sentence": "It is impolite to laugh at other people."},
                {"id": "g6d1-40", "word": "smile", "phonetic": "/smaɪl/", "meaning": "微笑；笑", "example_sentence": "She always has a warm smile on her face."},
                {"id": "g6d1-41", "word": "feather", "phonetic": "/ˈfeðə(r)/", "meaning": "羽毛", "example_sentence": "The bird has colorful feathers."},
                {"id": "g6d1-42", "word": "future", "phonetic": "/ˈfjuːtʃə(r)/", "meaning": "将来；未来", "example_sentence": "In the future, I want to be a scientist."},
                {"id": "g6d1-43", "word": "skill", "phonetic": "/skɪl/", "meaning": "技巧；技艺", "example_sentence": "Reading is an important skill for learning."},
                {"id": "g6d1-44", "word": "unique", "phonetic": "/juˈniːk/", "meaning": "唯一的；独一无二的", "example_sentence": "Every snowflake has a unique pattern."},
                {"id": "g6d1-45", "word": "mean", "phonetic": "/miːn/", "meaning": "意思是", "example_sentence": "What does this word mean in English?"},
                {"id": "g6d1-46", "word": "noticeboard", "phonetic": "/ˈnəʊtɪsbɔːd/", "meaning": "布告栏；布告板", "example_sentence": "Please check the noticeboard for the latest announcements."},
                {"id": "g6d1-47", "word": "would", "phonetic": "/wʊd/", "meaning": "（客气地建议或邀请）将；将会", "example_sentence": "Would you like to join us for dinner?"},
            ],
        },
        {
            "id": "sys-grade6-down-u2",
            "name": "六年级下册 Unit 2",
            "grade": "小学",
            "description": "上海版六年级下册 Unit 2 英语词汇",
            "created_at": "2024-01-01",
            "words": [
                {"id": "g6d2-1", "word": "rule", "phonetic": "/ruːl/", "meaning": "规则；规章", "example_sentence": "We must follow the rules of the school."},
                {"id": "g6d2-2", "word": "underground", "phonetic": "/ˈʌndəɡraʊnd/", "meaning": "地铁；地下铁路系统", "example_sentence": "The underground in London is also called the Tube."},
                {"id": "g6d2-3", "word": "lean", "phonetic": "/liːn/", "meaning": "倚靠；倾斜", "example_sentence": "Please do not lean against the glass door."},
                {"id": "g6d2-4", "word": "litter", "phonetic": "/ˈlɪtə(r)/", "meaning": "乱扔", "example_sentence": "We should never litter in public places."},
                {"id": "g6d2-5", "word": "gap", "phonetic": "/ɡæp/", "meaning": "缺口；间隙", "example_sentence": "There is a gap between the two buildings."},
                {"id": "g6d2-6", "word": "else", "phonetic": "/els/", "meaning": "其他", "example_sentence": "What else would you like to know?"},
                {"id": "g6d2-7", "word": "station", "phonetic": "/ˈsteɪʃn/", "meaning": "车站；（服务）台", "example_sentence": "We met at the train station this morning."},
                {"id": "g6d2-8", "word": "announcement", "phonetic": "/əˈnaʊnsmənt/", "meaning": "公告；通告", "example_sentence": "The announcement told passengers about the delay."},
                {"id": "g6d2-9", "word": "passenger", "phonetic": "/ˈpæsɪndʒə(r)/", "meaning": "乘客；旅客", "example_sentence": "Every passenger must wear a seatbelt on the plane."},
                {"id": "g6d2-10", "word": "lift", "phonetic": "/lɪft/", "meaning": "电梯；升降机", "example_sentence": "We took the lift to the tenth floor."},
                {"id": "g6d2-11", "word": "platform", "phonetic": "/ˈplætfɔːm/", "meaning": "站台", "example_sentence": "The train is waiting at platform number three."},
                {"id": "g6d2-12", "word": "line", "phonetic": "/laɪn/", "meaning": "线；线条", "example_sentence": "Stand in a straight line, please."},
                {"id": "g6d2-13", "word": "rush", "phonetic": "/rʌʃ/", "meaning": "迅速移动", "example_sentence": "Do not rush! We have plenty of time."},
                {"id": "g6d2-14", "word": "smoke", "phonetic": "/sməʊk/", "meaning": "吸烟；抽烟", "example_sentence": "It is not allowed to smoke in this building."},
                {"id": "g6d2-15", "word": "seat", "phonetic": "/siːt/", "meaning": "座位", "example_sentence": "Please take a seat and wait for your turn."},
                {"id": "g6d2-16", "word": "anyone", "phonetic": "/ˈeniwʌn/", "meaning": "任何人", "example_sentence": "Does anyone know the answer to this question?"},
                {"id": "g6d2-17", "word": "leave", "phonetic": "/liːv/", "meaning": "留下；离开", "example_sentence": "Do not leave your bag on the bus."},
                {"id": "g6d2-18", "word": "rubbish", "phonetic": "/ˈrʌbɪʃ/", "meaning": "垃圾；废弃物", "example_sentence": "Please put the rubbish in the bin."},
                {"id": "g6d2-19", "word": "glove", "phonetic": "/ɡlʌv/", "meaning": "手套", "example_sentence": "I need to wear gloves because it is very cold outside."},
                {"id": "g6d2-20", "word": "broken", "phonetic": "/ˈbrəʊkən/", "meaning": "破损的；伤残的", "example_sentence": "My phone screen is broken and I need to fix it."},
                {"id": "g6d2-21", "word": "container", "phonetic": "/kənˈteɪnə(r)/", "meaning": "容器", "example_sentence": "She poured the water into a glass container."},
                {"id": "g6d2-22", "word": "ready", "phonetic": "/ˈredi/", "meaning": "准备好的；准备完毕的", "example_sentence": "Are you ready for the English test?"},
                {"id": "g6d2-23", "word": "follow", "phonetic": "/ˈfɒləʊ/", "meaning": "遵循；跟随", "example_sentence": "Please follow me to the classroom."},
                {"id": "g6d2-24", "word": "stay", "phonetic": "/steɪ/", "meaning": "保持；继续是", "example_sentence": "Stay here and wait for me to come back."},
                {"id": "g6d2-25", "word": "grow", "phonetic": "/ɡrəʊ/", "meaning": "逐渐变得；逐渐成为", "example_sentence": "Plants need sunlight and water to grow."},
                {"id": "g6d2-26", "word": "important", "phonetic": "/ɪmˈpɔːtnt/", "meaning": "重要的；有重大影响的", "example_sentence": "It is important to eat breakfast every morning."},
                {"id": "g6d2-27", "word": "take turns", "phonetic": "", "meaning": "轮流；依次", "example_sentence": "The students take turns to answer the teacher's question."},
                {"id": "g6d2-28", "word": "model", "phonetic": "/ˈmɒdl/", "meaning": "模型", "example_sentence": "He built a model airplane all by himself."},
                {"id": "g6d2-29", "word": "pay", "phonetic": "/peɪ/", "meaning": "给予（注意等）；付费", "example_sentence": "I need to pay for this book at the counter."},
                {"id": "g6d2-30", "word": "attention", "phonetic": "/əˈtenʃn/", "meaning": "注意；关注", "example_sentence": "Please pay attention when the teacher is speaking."},
                {"id": "g6d2-31", "word": "pay attention to", "phonetic": "", "meaning": "（对某人或某事）注意", "example_sentence": "Please pay attention to what the teacher says in class."},
                {"id": "g6d2-32", "word": "dream", "phonetic": "/driːm/", "meaning": "梦；梦想", "example_sentence": "I had a wonderful dream about flying last night."},
                {"id": "g6d2-33", "word": "gate", "phonetic": "/ɡeɪt/", "meaning": "大门", "example_sentence": "The train leaves from gate number five."},
            ],
        },
        {
            "id": "sys-grade6-down-u3",
            "name": "六年级下册 Unit 3",
            "grade": "小学",
            "description": "上海版六年级下册 Unit 3 英语词汇",
            "created_at": "2024-01-01",
            "words": [
                {"id": "g6d3-1", "word": "festival", "phonetic": "/ˈfestɪvl/", "meaning": "节日", "example_sentence": "The Spring Festival is the most important festival in China."},
                {"id": "g6d3-2", "word": "across", "phonetic": "/əˈkrɒs/", "meaning": "横过；穿过", "example_sentence": "She walked across the bridge to get to school."},
                {"id": "g6d3-3", "word": "culture", "phonetic": "/ˈkʌltʃə(r)/", "meaning": "文化", "example_sentence": "Learning about different cultures is very interesting."},
                {"id": "g6d3-4", "word": "luck", "phonetic": "/lʌk/", "meaning": "机遇；命运；运气", "example_sentence": "Good luck with your exam tomorrow!"},
                {"id": "g6d3-5", "word": "spring roll", "phonetic": "/ˌsprɪŋ ˈrəʊl/", "meaning": "春卷", "example_sentence": "Spring rolls are a traditional Chinese food eaten during the Spring Festival."},
                {"id": "g6d3-6", "word": "porridge", "phonetic": "/ˈpɒrɪdʒ/", "meaning": "粥", "example_sentence": "I have porridge and an egg for breakfast every day."},
                {"id": "g6d3-7", "word": "lucky", "phonetic": "/ˈlʌki/", "meaning": "有好运的；运气好的；幸运的", "example_sentence": "I was lucky to find my lost watch."},
                {"id": "g6d3-8", "word": "click", "phonetic": "/klɪk/", "meaning": "（在计算机屏幕上用鼠标）点击，单击", "example_sentence": "Click the button to submit your answer."},
                {"id": "g6d3-9", "word": "eve", "phonetic": "/iːv/", "meaning": "前夜；前夕", "example_sentence": "On New Year's Eve, we watch fireworks together."},
                {"id": "g6d3-10", "word": "tradition", "phonetic": "/trəˈdɪʃn/", "meaning": "传统", "example_sentence": "It is a Chinese tradition to eat dumplings during the Spring Festival."},
                {"id": "g6d3-11", "word": "country", "phonetic": "/ˈkʌntri/", "meaning": "国家", "example_sentence": "China is a large country with a long history."},
                {"id": "g6d3-12", "word": "wealth", "phonetic": "/welθ/", "meaning": "钱财；财富", "example_sentence": "Health is more important than wealth."},
                {"id": "g6d3-13", "word": "hope", "phonetic": "/həʊp/", "meaning": "希望；期望（某事发生）", "example_sentence": "I hope you have a wonderful holiday."},
                {"id": "g6d3-14", "word": "pass", "phonetic": "/pɑːs/", "meaning": "给；递；传递", "example_sentence": "Please pass me the salt on the table."},
                {"id": "g6d3-15", "word": "pass on", "phonetic": "", "meaning": "传递；转交；（用后）递给，传给", "example_sentence": "Please pass on this message to your classmates."},
                {"id": "g6d3-16", "word": "midnight", "phonetic": "/ˈmɪdnaɪt/", "meaning": "午夜", "example_sentence": "The clock struck midnight and the new year began."},
                {"id": "g6d3-17", "word": "international", "phonetic": "/ˌɪntəˈnæʃnəl/", "meaning": "国际的", "example_sentence": "English is an international language spoken all over the world."},
                {"id": "g6d3-18", "word": "event", "phonetic": "/ɪˈvent/", "meaning": "公开活动；事件", "example_sentence": "The sports event will be held next Friday."},
                {"id": "g6d3-19", "word": "square", "phonetic": "/skweə(r)/", "meaning": "广场", "example_sentence": "People gather in the square to celebrate the festival."},
                {"id": "g6d3-20", "word": "symphony", "phonetic": "/ˈsɪmfəni/", "meaning": "交响乐；交响曲", "example_sentence": "The symphony orchestra played beautiful music last night."},
                {"id": "g6d3-21", "word": "theatre", "phonetic": "/ˈθɪətə(r)/", "meaning": "戏院；剧场；露天剧场", "example_sentence": "We went to the theatre to watch a play."},
                {"id": "g6d3-22", "word": "firework", "phonetic": "/ˈfaɪəwɜːk/", "meaning": "烟火；烟花", "example_sentence": "The fireworks lit up the night sky beautifully."},
                {"id": "g6d3-23", "word": "concert", "phonetic": "/ˈkɒnsət/", "meaning": "音乐会；演奏会", "example_sentence": "I went to a pop concert with my friends last weekend."},
                {"id": "g6d3-24", "word": "prince", "phonetic": "/prɪns/", "meaning": "王子", "example_sentence": "The prince lived in a magnificent castle."},
                {"id": "g6d3-25", "word": "check", "phonetic": "/tʃek/", "meaning": "查明；查看；核实", "example_sentence": "Please check your homework before handing it in."},
                {"id": "g6d3-26", "word": "check out", "phonetic": "", "meaning": "查看；看一看", "example_sentence": "Check out this amazing video about space!"},
                {"id": "g6d3-27", "word": "information", "phonetic": "/ˌɪnfəˈmeɪʃn/", "meaning": "信息；消息；情报；资料；资讯", "example_sentence": "You can find a lot of information on the internet."},
                {"id": "g6d3-28", "word": "since", "phonetic": "/sɪns/", "meaning": "自……以来；自……以后", "example_sentence": "I have studied English since I was six years old."},
                {"id": "g6d3-29", "word": "performance", "phonetic": "/pəˈfɔːməns/", "meaning": "表演", "example_sentence": "Her performance in the show was amazing."},
                {"id": "g6d3-30", "word": "really", "phonetic": "/ˈriːəli/", "meaning": "事实上；真正地", "example_sentence": "I really enjoy reading English stories."},
                {"id": "g6d3-31", "word": "perform", "phonetic": "/pəˈfɔːm/", "meaning": "表演；演出", "example_sentence": "The students will perform a play at the school show."},
                {"id": "g6d3-32", "word": "invite", "phonetic": "/ɪnˈvaɪt/", "meaning": "邀请", "example_sentence": "I would like to invite you to my birthday party."},
                {"id": "g6d3-33", "word": "hate", "phonetic": "/heɪt/", "meaning": "讨厌；憎恶", "example_sentence": "I hate getting up early on cold winter mornings."},
                {"id": "g6d3-34", "word": "refuse", "phonetic": "/rɪˈfjuːz/", "meaning": "回绝；拒绝", "example_sentence": "He refused to give up and kept trying."},
                {"id": "g6d3-35", "word": "celebrate", "phonetic": "/ˈselɪbreɪt/", "meaning": "庆祝；庆贺", "example_sentence": "We celebrate the Spring Festival with our family."},
                {"id": "g6d3-36", "word": "calendar", "phonetic": "/ˈkælɪndə(r)/", "meaning": "日历；历法", "example_sentence": "I marked the date on my calendar so I would not forget."},
                {"id": "g6d3-37", "word": "lunar calendar", "phonetic": "", "meaning": "农历", "example_sentence": "The Spring Festival date is based on the lunar calendar."},
                {"id": "g6d3-38", "word": "full", "phonetic": "/fʊl/", "meaning": "满的", "example_sentence": "The glass is full of water."},
                {"id": "g6d3-39", "word": "post", "phonetic": "/pəʊst/", "meaning": "发帖；寄；邮寄", "example_sentence": "She posted some photos from her holiday on the internet."},
                {"id": "g6d3-40", "word": "mostly", "phonetic": "/ˈməʊstli/", "meaning": "主要地；一般地；通常", "example_sentence": "I mostly read books in my free time."},
                {"id": "g6d3-41", "word": "tonight", "phonetic": "/təˈnaɪt/", "meaning": "今晚", "example_sentence": "We are going to the cinema tonight."},
                {"id": "g6d3-42", "word": "harvest", "phonetic": "/ˈhɑːvɪst/", "meaning": "收获；收获季节", "example_sentence": "The autumn harvest was very good this year."},
                {"id": "g6d3-43", "word": "traditional", "phonetic": "/trəˈdɪʃənl/", "meaning": "传统的；习俗的", "example_sentence": "Traditional Chinese food is delicious."},
                {"id": "g6d3-44", "word": "nut", "phonetic": "/nʌt/", "meaning": "坚果", "example_sentence": "I like to eat nuts as a snack."},
                {"id": "g6d3-45", "word": "sugar", "phonetic": "/ˈʃʊɡə(r)/", "meaning": "食糖", "example_sentence": "Would you like some sugar in your tea?"},
                {"id": "g6d3-46", "word": "experience", "phonetic": "/ɪkˈspɪəriəns/", "meaning": "经历；经验", "example_sentence": "Traveling abroad was a wonderful experience for me."},
                {"id": "g6d3-47", "word": "meal", "phonetic": "/miːl/", "meaning": "早（或午、晚）餐；一顿饭", "example_sentence": "We usually have three meals a day: breakfast, lunch and dinner."},
                {"id": "g6d3-48", "word": "count", "phonetic": "/kaʊnt/", "meaning": "数数；计算", "example_sentence": "Can you count from one to one hundred in English?"},
            ],
        },
        {
            "id": "sys-grade6-down-u4",
            "name": "六年级下册 Unit 4",
            "grade": "小学",
            "description": "上海版六年级下册 Unit 4 英语词汇",
            "created_at": "2024-01-01",
            "words": [
                {"id": "g6d4-1", "word": "search", "phonetic": "/sɜːtʃ/", "meaning": "搜索；搜寻；搜查；查找", "example_sentence": "I searched the internet for information about pandas."},
                {"id": "g6d4-2", "word": "airport", "phonetic": "/ˈeəpɔːt/", "meaning": "机场", "example_sentence": "We arrived at the airport two hours before the flight."},
                {"id": "g6d4-3", "word": "location", "phonetic": "/ləʊˈkeɪʃn/", "meaning": "地方；地点；位置", "example_sentence": "The hotel is in a great location near the beach."},
                {"id": "g6d4-4", "word": "capital", "phonetic": "/ˈkæpɪtl/", "meaning": "首都；国都", "example_sentence": "Beijing is the capital of China."},
                {"id": "g6d4-5", "word": "wet", "phonetic": "/wet/", "meaning": "湿的；潮湿的", "example_sentence": "My clothes got wet in the rain."},
                {"id": "g6d4-6", "word": "foggy", "phonetic": "/ˈfɒɡi/", "meaning": "有雾的", "example_sentence": "It was so foggy that we could not see the road clearly."},
                {"id": "g6d4-7", "word": "north", "phonetic": "/nɔːθ/", "meaning": "北；北方", "example_sentence": "The city is in the north of China."},
                {"id": "g6d4-8", "word": "quite", "phonetic": "/kwaɪt/", "meaning": "相当；非常", "example_sentence": "The film was quite good but not the best I have seen."},
                {"id": "g6d4-9", "word": "temperature", "phonetic": "/ˈtemprətʃə(r)/", "meaning": "温度；气温", "example_sentence": "The temperature dropped below zero last night."},
                {"id": "g6d4-10", "word": "drop", "phonetic": "/drɒp/", "meaning": "降低；减少", "example_sentence": "The temperature will drop by five degrees tomorrow."},
                {"id": "g6d4-11", "word": "degree", "phonetic": "/dɪˈɡriː/", "meaning": "度；度数", "example_sentence": "Water boils at one hundred degrees Celsius."},
                {"id": "g6d4-12", "word": "dry", "phonetic": "/draɪ/", "meaning": "干的；干燥的", "example_sentence": "The weather is very dry in the desert."},
                {"id": "g6d4-13", "word": "south", "phonetic": "/saʊθ/", "meaning": "南部；南方", "example_sentence": "Birds fly south for the winter."},
                {"id": "g6d4-14", "word": "still", "phonetic": "/stɪl/", "meaning": "还；仍然", "example_sentence": "It is still raining outside."},
                {"id": "g6d4-15", "word": "wind", "phonetic": "/wɪnd/", "meaning": "风", "example_sentence": "The wind blew the hat off his head."},
                {"id": "g6d4-16", "word": "cloud", "phonetic": "/klaʊd/", "meaning": "云；云朵", "example_sentence": "A dark cloud appeared in the sky."},
                {"id": "g6d4-17", "word": "fog", "phonetic": "/fɒɡ/", "meaning": "雾", "example_sentence": "Thick fog made it difficult to drive."},
                {"id": "g6d4-18", "word": "skate", "phonetic": "/skeɪt/", "meaning": "滑冰；溜冰", "example_sentence": "Children love to skate on the ice in winter."},
                {"id": "g6d4-19", "word": "picnic", "phonetic": "/ˈpɪknɪk/", "meaning": "野餐", "example_sentence": "We had a lovely picnic in the park last Sunday."},
                {"id": "g6d4-20", "word": "news", "phonetic": "/njuːz/", "meaning": "新闻；报道", "example_sentence": "I watch the news every evening to know what is happening."},
                {"id": "g6d4-21", "word": "heat", "phonetic": "/hiːt/", "meaning": "热；高温", "example_sentence": "The heat of the sun can be very strong in summer."},
                {"id": "g6d4-22", "word": "wave", "phonetic": "/weɪv/", "meaning": "海浪；波浪", "example_sentence": "A huge wave crashed against the rocks."},
                {"id": "g6d4-23", "word": "heatwave", "phonetic": "/ˈhiːtweɪv/", "meaning": "酷热期；热浪", "example_sentence": "A heatwave hit the city last week."},
                {"id": "g6d4-24", "word": "hit", "phonetic": "/hɪt/", "meaning": "达到（某水平）", "example_sentence": "The typhoon will hit the coast tomorrow morning."},
                {"id": "g6d4-25", "word": "several", "phonetic": "/ˈsevrəl/", "meaning": "几个；数个", "example_sentence": "I have read several books about ancient China."},
                {"id": "g6d4-26", "word": "break", "phonetic": "/breɪk/", "meaning": "打破；破；裂；碎", "example_sentence": "Be careful not to break the glass."},
                {"id": "g6d4-27", "word": "record", "phonetic": "/ˈrekɔːd/", "meaning": "纪录；记录", "example_sentence": "She set a new world record in the 100-metre race."},
                {"id": "g6d4-28", "word": "reach", "phonetic": "/riːtʃ/", "meaning": "增加到；达到", "example_sentence": "The temperature will reach thirty-five degrees today."},
                {"id": "g6d4-29", "word": "break out", "phonetic": "", "meaning": "突然开始；爆发", "example_sentence": "A fire broke out in the building last night."},
                {"id": "g6d4-30", "word": "area", "phonetic": "/ˈeəriə/", "meaning": "地区，地域", "example_sentence": "This area is known for its beautiful scenery."},
                {"id": "g6d4-31", "word": "action", "phonetic": "/ˈækʃn/", "meaning": "行动", "example_sentence": "We must take action to protect the environment."},
                {"id": "g6d4-32", "word": "pupil", "phonetic": "/ˈpjuːpl/", "meaning": "学生；小学生", "example_sentence": "Every pupil must wear a school uniform."},
                {"id": "g6d4-33", "word": "uniform", "phonetic": "/ˈjuːnɪfɔːm/", "meaning": "制服；校服", "example_sentence": "Students must wear their uniforms to school."},
                {"id": "g6d4-34", "word": "indoors", "phonetic": "/ˌɪnˈdɔːz/", "meaning": "在室内", "example_sentence": "We stayed indoors because it was raining heavily."},
                {"id": "g6d4-35", "word": "leaf", "phonetic": "/liːf/", "meaning": "叶子", "example_sentence": "In autumn, the leaves on the trees turn yellow and fall."},
                {"id": "g6d4-36", "word": "fact", "phonetic": "/fækt/", "meaning": "现实；实际情况", "example_sentence": "It is a fact that the Earth goes around the Sun."},
                {"id": "g6d4-37", "word": "in fact", "phonetic": "", "meaning": "事实上", "example_sentence": "In fact, learning English can be a lot of fun."},
                {"id": "g6d4-38", "word": "average", "phonetic": "/ˈævərɪdʒ/", "meaning": "平均的", "example_sentence": "The average temperature here is about twenty degrees."},
                {"id": "g6d4-39", "word": "increase", "phonetic": "/ɪnˈkriːs/", "meaning": "增长；增加", "example_sentence": "The population of the city continues to increase."},
                {"id": "g6d4-40", "word": "coal", "phonetic": "/kəʊl/", "meaning": "煤", "example_sentence": "Coal is used as fuel in many power stations."},
                {"id": "g6d4-41", "word": "cause", "phonetic": "/kɔːz/", "meaning": "引起；使发生", "example_sentence": "Pollution causes many health problems."},
                {"id": "g6d4-42", "word": "worse", "phonetic": "/wɜːs/", "meaning": "更差的；更糟的", "example_sentence": "The weather is getting worse and worse."},
                {"id": "g6d4-43", "word": "soon", "phonetic": "/suːn/", "meaning": "很快；马上；不久", "example_sentence": "I will be back home soon."},
                {"id": "g6d4-44", "word": "regards", "phonetic": "/rɪˈɡɑːdz/", "meaning": "致意；问候", "example_sentence": "Please give my regards to your family."},
            ],
        },
        {
            "id": "sys-grade6-down-u5",
            "name": "六年级下册 Unit 5",
            "grade": "小学",
            "description": "上海版六年级下册 Unit 5 英语词汇",
            "created_at": "2024-01-01",
            "words": [
                {"id": "g6d5-1", "word": "neighbourhood", "phonetic": "/ˈneɪbəhʊd/", "meaning": "街区；邻近的地方", "example_sentence": "There is a small park in my neighbourhood."},
                {"id": "g6d5-2", "word": "build", "phonetic": "/bɪld/", "meaning": "创建；建造", "example_sentence": "They are building a new school near my house."},
                {"id": "g6d5-3", "word": "reduce", "phonetic": "/rɪˈdjuːs/", "meaning": "减少；缩小", "example_sentence": "We should reduce the amount of waste we produce."},
                {"id": "g6d5-4", "word": "recycle", "phonetic": "/ˌriːˈsaɪkl/", "meaning": "回收利用", "example_sentence": "We should recycle paper, glass and plastic bottles."},
                {"id": "g6d5-5", "word": "bottle", "phonetic": "/ˈbɒtl/", "meaning": "瓶子", "example_sentence": "She drank a bottle of water after running."},
                {"id": "g6d5-6", "word": "repair", "phonetic": "/rɪˈpeə(r)/", "meaning": "修理；修补", "example_sentence": "My father is going to repair the broken chair."},
                {"id": "g6d5-7", "word": "item", "phonetic": "/ˈaɪtəm/", "meaning": "一件物品", "example_sentence": "Each item in the shop has a price tag."},
                {"id": "g6d5-8", "word": "sort", "phonetic": "/sɔːt/", "meaning": "整理；把……分类", "example_sentence": "Please sort the rubbish into different bins."},
                {"id": "g6d5-9", "word": "cloth", "phonetic": "/klɒθ/", "meaning": "织物；布料", "example_sentence": "She wiped the table with a damp cloth."},
                {"id": "g6d5-10", "word": "pick", "phonetic": "/pɪk/", "meaning": "拿起；挑选；选择", "example_sentence": "You can pick any book you like from the shelf."},
                {"id": "g6d5-11", "word": "pick up", "phonetic": "", "meaning": "捡起；拾起", "example_sentence": "He picked up a coin from the ground."},
                {"id": "g6d5-12", "word": "plastic", "phonetic": "/ˈplæstɪk/", "meaning": "塑料的", "example_sentence": "We should use less plastic to protect the environment."},
                {"id": "g6d5-13", "word": "waste", "phonetic": "/weɪst/", "meaning": "废物；垃圾", "example_sentence": "Do not waste food. Eat everything on your plate."},
                {"id": "g6d5-14", "word": "electricity", "phonetic": "/ɪˌlekˈtrɪsəti/", "meaning": "电；电能", "example_sentence": "We use electricity for lighting and cooking."},
                {"id": "g6d5-15", "word": "tap", "phonetic": "/tæp/", "meaning": "水龙头", "example_sentence": "Remember to turn off the tap when you brush your teeth."},
                {"id": "g6d5-16", "word": "brush", "phonetic": "/brʌʃ/", "meaning": "（用刷子）刷净，刷亮，刷平顺", "example_sentence": "You should brush your teeth twice a day."},
                {"id": "g6d5-17", "word": "tooth", "phonetic": "/tuːθ/", "meaning": "牙；齿", "example_sentence": "The little girl lost her first tooth."},
                {"id": "g6d5-18", "word": "bin", "phonetic": "/bɪn/", "meaning": "垃圾箱", "example_sentence": "Please put the rubbish in the bin, not on the floor."},
                {"id": "g6d5-19", "word": "save", "phonetic": "/seɪv/", "meaning": "节省；节约；救", "example_sentence": "We should save water because it is precious."},
                {"id": "g6d5-20", "word": "mix", "phonetic": "/mɪks/", "meaning": "混合；融合", "example_sentence": "Mix the flour and sugar together in a bowl."},
                {"id": "g6d5-21", "word": "store", "phonetic": "/stɔː(r)/", "meaning": "商店；店铺", "example_sentence": "I bought some milk from the store near my home."},
                {"id": "g6d5-22", "word": "even", "phonetic": "/ˈiːvn/", "meaning": "甚至，连，即使", "example_sentence": "Even a small child can understand this story."},
                {"id": "g6d5-23", "word": "huge", "phonetic": "/hjuːdʒ/", "meaning": "巨大的；极多的；程度高的", "example_sentence": "The elephant is a huge animal."},
                {"id": "g6d5-24", "word": "government", "phonetic": "/ˈɡʌvənmənt/", "meaning": "政府；内阁", "example_sentence": "The government is building more parks in the city."},
                {"id": "g6d5-25", "word": "encourage", "phonetic": "/ɪnˈkʌrɪdʒ/", "meaning": "支持；鼓励；激励", "example_sentence": "My teacher always encourages me to try my best."},
                {"id": "g6d5-26", "word": "public", "phonetic": "/ˈpʌblɪk/", "meaning": "公共的；公立的", "example_sentence": "Smoking is not allowed in public places."},
                {"id": "g6d5-27", "word": "transport", "phonetic": "/ˈtrænspɔːt/", "meaning": "交通工具；旅行方式", "example_sentence": "Public transport in this city is very convenient."},
                {"id": "g6d5-28", "word": "environmental", "phonetic": "/ɪnˌvaɪrənˈmentl/", "meaning": "环境的", "example_sentence": "Environmental protection is everyone's responsibility."},
                {"id": "g6d5-29", "word": "electric", "phonetic": "/ɪˈlektrɪk/", "meaning": "电的；电动的", "example_sentence": "My family bought a new electric car last month."},
                {"id": "g6d5-30", "word": "building", "phonetic": "/ˈbɪldɪŋ/", "meaning": "建筑物；房子；楼房", "example_sentence": "That tall building is the new shopping centre."},
                {"id": "g6d5-31", "word": "low", "phonetic": "/ləʊ/", "meaning": "低于平均水平的；低的；矮的", "example_sentence": "The price of this shirt is very low."},
                {"id": "g6d5-32", "word": "energy", "phonetic": "/ˈenədʒi/", "meaning": "能源", "example_sentence": "Solar energy is clean and renewable."},
                {"id": "g6d5-33", "word": "low-energy", "phonetic": "/ləʊ ˈenədʒi/", "meaning": "低能耗的", "example_sentence": "Low-energy buildings help protect the environment."},
                {"id": "g6d5-34", "word": "however", "phonetic": "/haʊˈevə(r)/", "meaning": "然而", "example_sentence": "I like football. However, my brother prefers basketball."},
                {"id": "g6d5-35", "word": "alone", "phonetic": "/əˈləʊn/", "meaning": "独自", "example_sentence": "She does not like to stay home alone."},
                {"id": "g6d5-36", "word": "planet", "phonetic": "/ˈplænɪt/", "meaning": "行星", "example_sentence": "The Earth is the only planet we know that has life."},
                {"id": "g6d5-37", "word": "mankind", "phonetic": "/mænˈkaɪnd/", "meaning": "人类", "example_sentence": "Space exploration benefits all of mankind."},
                {"id": "g6d5-38", "word": "daily", "phonetic": "/ˈdeɪli/", "meaning": "每日的；日常的", "example_sentence": "Reading English newspapers is part of my daily routine."},
            ],
        },
        {
            "id": "sys-grade6-down-u6",
            "name": "六年级下册 Unit 6",
            "grade": "小学",
            "description": "上海版六年级下册 Unit 6 英语词汇",
            "created_at": "2024-01-01",
            "words": [
                {"id": "g6d6-1", "word": "changer", "phonetic": "/ˈtʃeɪndʒə(r)/", "meaning": "改变者；改进者", "example_sentence": "She is a changer who makes the world a better place."},
                {"id": "g6d6-2", "word": "scientist", "phonetic": "/ˈsaɪəntɪst/", "meaning": "科学家", "example_sentence": "The scientist spent years studying the disease."},
                {"id": "g6d6-3", "word": "change", "phonetic": "/tʃeɪndʒ/", "meaning": "改变；变化", "example_sentence": "People should change their bad habits."},
                {"id": "g6d6-4", "word": "publish", "phonetic": "/ˈpʌblɪʃ/", "meaning": "出版", "example_sentence": "She wants to publish a book about her travels."},
                {"id": "g6d6-5", "word": "theory", "phonetic": "/ˈθɪəri/", "meaning": "学说；理论", "example_sentence": "The scientist had a new theory about how the universe began."},
                {"id": "g6d6-6", "word": "invent", "phonetic": "/ɪnˈvent/", "meaning": "发明；创造", "example_sentence": "Who invented the telephone?"},
                {"id": "g6d6-7", "word": "inexpensive", "phonetic": "/ˌɪnkˈspensɪv/", "meaning": "廉价的；不昂贵的", "example_sentence": "This inexpensive book is full of useful knowledge."},
                {"id": "g6d6-8", "word": "bulb", "phonetic": "/bʌlb/", "meaning": "电灯泡", "example_sentence": "Thomas Edison invented the light bulb."},
                {"id": "g6d6-9", "word": "discover", "phonetic": "/dɪˈskʌvə(r)/", "meaning": "发现", "example_sentence": "Scientists continue to discover new species in the ocean."},
                {"id": "g6d6-10", "word": "general", "phonetic": "/ˈdʒenrəl/", "meaning": "全体的；普遍的；总的", "example_sentence": "The general opinion is that exercise is good for health."},
                {"id": "g6d6-11", "word": "smart", "phonetic": "/smɑːt/", "meaning": "聪明的；机敏的", "example_sentence": "She is the smartest student in our class."},
                {"id": "g6d6-12", "word": "inventor", "phonetic": "/ɪnˈventə(r)/", "meaning": "发明者；发明家", "example_sentence": "Thomas Edison was a famous American inventor."},
                {"id": "g6d6-13", "word": "real", "phonetic": "/ˈriːəl/", "meaning": "真正的", "example_sentence": "Is this a real diamond or a fake one?"},
                {"id": "g6d6-14", "word": "power", "phonetic": "/ˈpaʊə(r)/", "meaning": "电；电力供应", "example_sentence": "The power went out during the storm last night."},
                {"id": "g6d6-15", "word": "power station", "phonetic": "", "meaning": "发电站；发电厂", "example_sentence": "The power station provides electricity to the whole city."},
                {"id": "g6d6-16", "word": "die", "phonetic": "/daɪ/", "meaning": "死亡", "example_sentence": "Plants will die without water."},
                {"id": "g6d6-17", "word": "successful", "phonetic": "/səkˈsesfl/", "meaning": "获得成功的", "example_sentence": "She worked hard and became a successful doctor."},
                {"id": "g6d6-18", "word": "invention", "phonetic": "/ɪnˈvenʃn/", "meaning": "发明；创造", "example_sentence": "The invention of the internet changed the world forever."},
                {"id": "g6d6-19", "word": "saver", "phonetic": "/ˈseɪvə(r)/", "meaning": "救助者；救星", "example_sentence": "He is a money saver who never spends on unnecessary things."},
                {"id": "g6d6-20", "word": "medicine", "phonetic": "/ˈmedsn/", "meaning": "医学；药", "example_sentence": "The doctor told me to take the medicine three times a day."},
                {"id": "g6d6-21", "word": "Traditional Chinese Medicine", "phonetic": "", "meaning": "中医药", "example_sentence": "Traditional Chinese Medicine has a history of thousands of years."},
                {"id": "g6d6-22", "word": "spend", "phonetic": "/spend/", "meaning": "花（时间）；度过", "example_sentence": "I spend about one hour on English homework every day."},
                {"id": "g6d6-23", "word": "sick", "phonetic": "/sɪk/", "meaning": "生病的；有病的", "example_sentence": "She felt sick and went to see the doctor."},
                {"id": "g6d6-24", "word": "soldier", "phonetic": "/ˈsəʊldʒə(r)/", "meaning": "军人；士兵", "example_sentence": "The brave soldier protected the country."},
                {"id": "g6d6-25", "word": "lose", "phonetic": "/luːz/", "meaning": "遗失；丢失", "example_sentence": "Be careful not to lose your keys."},
                {"id": "g6d6-26", "word": "admire", "phonetic": "/ədˈmaɪə(r)/", "meaning": "钦佩；赞赏；仰慕", "example_sentence": "I really admire her courage and determination."},
                {"id": "g6d6-27", "word": "pardon", "phonetic": "/ˈpɑːdn/", "meaning": "请再说一遍", "example_sentence": "Pardon? Could you say that again, please?"},
                {"id": "g6d6-28", "word": "herb", "phonetic": "/hɜːb/", "meaning": "药草；香草", "example_sentence": "Traditional Chinese herbs are used to treat many illnesses."},
                {"id": "g6d6-29", "word": "pain", "phonetic": "/peɪn/", "meaning": "疼痛", "example_sentence": "He felt a sharp pain in his stomach."},
                {"id": "g6d6-30", "word": "beg", "phonetic": "/beɡ/", "meaning": "乞讨；乞求", "example_sentence": "The poor man had to beg for food on the street."},
                {"id": "g6d6-31", "word": "beg your pardon", "phonetic": "", "meaning": "请原谅；请再说一遍", "example_sentence": "Beg your pardon, I did not hear what you said."},
                {"id": "g6d6-32", "word": "poem", "phonetic": "/ˈpəʊɪm/", "meaning": "诗", "example_sentence": "The student wrote a beautiful poem about spring."},
                {"id": "g6d6-33", "word": "act", "phonetic": "/ækt/", "meaning": "表演", "example_sentence": "The children like to act out stories in class."},
                {"id": "g6d6-34", "word": "marry", "phonetic": "/ˈmæri/", "meaning": "（和某人）结婚；嫁；娶", "example_sentence": "They plan to marry next summer."},
                {"id": "g6d6-35", "word": "married", "phonetic": "/ˈmærid/", "meaning": "已婚的；结婚的", "example_sentence": "Her parents have been married for twenty years."},
                {"id": "g6d6-36", "word": "create", "phonetic": "/kriˈeɪt/", "meaning": "创造；创作", "example_sentence": "The artist used recycled materials to create a sculpture."},
                {"id": "g6d6-37", "word": "character", "phonetic": "/ˈkærəktə(r)/", "meaning": "角色", "example_sentence": "My favourite character in the story is the brave little rabbit."},
                {"id": "g6d6-38", "word": "stage", "phonetic": "/steɪdʒ/", "meaning": "舞台", "example_sentence": "The students performed a play on the school stage."},
                {"id": "g6d6-39", "word": "million", "phonetic": "/ˈmɪljən/", "meaning": "一百万", "example_sentence": "The city has a population of over three million."},
                {"id": "g6d6-40", "word": "millions of", "phonetic": "", "meaning": "数以百万计的；很多", "example_sentence": "Millions of people around the world speak English."},
                {"id": "g6d6-41", "word": "mark", "phonetic": "/mɑːk/", "meaning": "做记号；做标记", "example_sentence": "Please mark the correct answer with a pen."},
                {"id": "g6d6-42", "word": "level", "phonetic": "/ˈlevl/", "meaning": "水平；标准", "example_sentence": "Her English is at a very high level."},
                {"id": "g6d6-43", "word": "until", "phonetic": "/ənˈtɪl/", "meaning": "直到……为止", "example_sentence": "Please wait here until I come back."},
                {"id": "g6d6-44", "word": "weigh", "phonetic": "/weɪ/", "meaning": "称重量；权衡", "example_sentence": "How much does this package weigh?"},
                {"id": "g6d6-45", "word": "weight", "phonetic": "/weɪt/", "meaning": "重量；分量", "example_sentence": "He lost a lot of weight by exercising every day."},
                {"id": "g6d6-46", "word": "stamp", "phonetic": "/stæmp/", "meaning": "邮票", "example_sentence": "My grandfather collects stamps from all over the world."},
            ],
        },
    ]


if __name__ == "__main__":
    init_db()
