"""
单词数据增强模块
提供：词性表（POS）、不规则动词变化表、补缺例句
供 database.py 数据增强和 routers 动态查询使用
"""

# ==================== 词性表（覆盖全部系统词库词汇） ====================
# n.=名词 v.=动词 adj.=形容词 adv.=副词 prep.=介词 pron.=代词
# conj.=连词 num.=数词 interj.=感叹词 phr.=短语
POS_MAP = {
    "abandon": "v.", "ability": "n.", "absence": "n.", "accept": "v.", "accomplish": "v.",
    "accurate": "adj.", "achieve": "v.", "across": "prep./adv.", "act": "v./n.", "action": "n.",
    "adequate": "adj.", "admire": "v.", "adventure": "n.", "afford": "v.", "afternoon": "n.",
    "aggressive": "adj.", "airport": "n.", "alone": "adj./adv.", "ambition": "n.", "analyze": "v.",
    "announcement": "n.", "anxiety": "n.", "anyone": "pron.", "anything": "pron.", "apple": "n.",
    "appreciate": "v.", "appropriate": "adj.", "approximately": "adv.", "april": "n.", "area": "n.",
    "argument": "n.", "artificial": "adj.", "attention": "n.", "attitude": "n.", "authority": "n.",
    "autumn": "n.", "average": "n./adj.", "badminton": "n.", "bag": "n.", "ball": "n.",
    "barely": "adv.", "basketball": "n.", "bathroom": "n.", "bedroom": "n.", "beg": "v.",
    "beg your pardon": "phr.", "beneficial": "adj.", "big": "adj.", "bin": "n.", "biology": "n.",
    "black": "adj./n.", "blackboard": "n.", "blue": "adj./n.", "book": "n.", "boring": "adj.",
    "bottle": "n.", "break": "v./n.", "break out": "v.phr.", "breakfast": "n.", "broken": "adj.",
    "brother": "n.", "brush": "v./n.", "build": "v.", "building": "n.", "bulb": "n.",
    "butterfly": "n.", "by subway": "phr.", "calendar": "n.", "camera": "n.", "camping": "n.",
    "capability": "n.", "capital": "n.", "cat": "n.", "cause": "v./n.", "ceiling": "n.",
    "celebrate": "v.", "chair": "n.", "challenge": "n./v.", "change": "v./n.", "changer": "n.",
    "character": "n.", "check": "v./n.", "check out": "v.phr.", "circumstances": "n.", "civilization": "n.",
    "classroom": "n.", "click": "v./n.", "climbing": "n.", "cloth": "n.", "cloud": "n.",
    "cloudy": "adj.", "coal": "n.", "cold": "adj./n.", "colleague": "n.", "commit": "v.",
    "communicate": "v.", "computer": "n.", "concert": "n.", "confidence": "n.", "consequence": "n.",
    "considerable": "adj.", "container": "n.", "contribute": "v.", "cooking": "n.", "cool": "adj.",
    "count": "v.", "country": "n.", "create": "v.", "creativity": "n.", "culture": "n.",
    "curly": "adj.", "cycling": "n.", "daily": "adj./adv.", "dance": "v./n.", "dangerous": "adj.",
    "degree": "n.", "desk": "n.", "develop": "v.", "die": "v.", "different": "adj.",
    "difficult": "adj.", "dinner": "n.", "discover": "v.", "dog": "n.", "door": "n.",
    "doubt": "n./v.", "dream": "n./v.", "drop": "v./n.", "drum": "n.", "dry": "adj.",
    "easy": "adj.", "education": "n.", "egg": "n.", "electric": "adj.", "electricity": "n.",
    "else": "adv.", "encourage": "v.", "energy": "n.", "environment": "n.", "environmental": "adj.",
    "eraser": "n.", "eve": "n.", "even": "adv.", "evening": "n.", "event": "n.",
    "exciting": "adj.", "experience": "n./v.", "explain": "v.", "fact": "n.", "fair": "adj.",
    "family": "n.", "fan": "n.", "fat": "adj.", "father": "n.", "favorite": "adj./n.",
    "feather": "n.", "february": "n.", "festival": "n.", "firework": "n.", "fish": "n./v.",
    "floor": "n.", "fog": "n.", "foggy": "adj.", "follow": "v.", "football": "n.",
    "forget": "v.", "friday": "n.", "friend": "n.", "full": "adj.", "future": "n.",
    "game": "n.", "gap": "n.", "gate": "n.", "general": "adj./n.", "geography": "n.",
    "girl": "n.", "glove": "n.", "go straight": "v.phr.", "good": "adj.", "government": "n.",
    "green": "adj./n.", "grow": "v.", "hall": "n.", "happy": "adj.", "harvest": "n./v.",
    "hat": "n.", "hate": "v.", "headphones": "n.", "heat": "n./v.", "heatwave": "n.",
    "herb": "n.", "hiking": "n.", "history": "n.", "hit": "v./n.", "hobby": "n.",
    "holiday": "n.", "hope": "v./n.", "hospital": "n.", "host": "v./n.", "hot": "adj.",
    "however": "adv.", "huge": "adj.", "ice": "n.", "imagination": "n.", "important": "adj.",
    "improve": "v.", "in fact": "phr.", "increase": "v./n.", "indoors": "adv.", "inexpensive": "adj.",
    "influence": "n./v.", "information": "n.", "interesting": "adj.", "international": "adj.", "invent": "v.",
    "invention": "n.", "inventor": "n.", "invite": "v.", "item": "n.", "january": "n.",
    "jeans": "n.", "juice": "n.", "keyboard": "n.", "kitchen": "n.", "kite": "n.",
    "knowledge": "n.", "laugh": "v.", "laugh at": "v.phr.", "leaf": "n.", "lean": "v.",
    "leave": "v.", "level": "n.", "library": "n.", "lift": "v./n.", "light": "n./adj.",
    "line": "n.", "lion": "n.", "litter": "v./n.", "living room": "n.", "location": "n.",
    "lose": "v.", "low": "adj.", "low-energy": "adj.", "luck": "n.", "lucky": "adj.",
    "lunar calendar": "n.", "lunch": "n.", "mankind": "n.", "march": "n.", "mark": "n./v.",
    "married": "adj.", "marry": "v.", "meal": "n.", "mean": "v.", "medicine": "n.",
    "microphone": "n.", "midnight": "n.", "milk": "n.", "million": "num.", "millions of": "phr.",
    "mix": "v.", "mobile phone": "n.", "model": "n.", "monday": "n.", "month": "n.",
    "morning": "n.", "mostly": "adv.", "mother": "n.", "mouse": "n.", "movie": "n.",
    "music": "n.", "neighbourhood": "n.", "news": "n.", "night": "n.", "north": "n./adj.",
    "nose": "n.", "notice": "v./n.", "noticeboard": "n.", "number": "n.", "nut": "n.",
    "opportunity": "n.", "orange": "n./adj.", "pain": "n.", "pardon": "v./n.", "partner": "n.",
    "pass": "v.", "pass on": "v.phr.", "passenger": "n.", "pay": "v.", "pay attention to": "v.phr.",
    "pen": "n.", "pencil": "n.", "perform": "v.", "performance": "n.", "person": "n.",
    "personality": "n.", "pick": "v.", "pick up": "v.phr.", "picnic": "n.", "planet": "n.",
    "plastic": "n./adj.", "platform": "n.", "poem": "n.", "pollution": "n.", "population": "n.",
    "porridge": "n.", "post": "n./v.", "power": "n.", "power station": "n.", "practice": "n./v.",
    "prince": "n.", "printer": "n.", "programme": "n.", "protect": "v.", "public": "adj./n.",
    "publish": "v.", "pupil": "n.", "queen": "n.", "quite": "adv.", "radio": "n.",
    "rain": "n./v.", "rainy": "adj.", "reach": "v.", "reading": "n.", "ready": "adj.",
    "real": "adj.", "really": "adv.", "record": "n./v.", "recycle": "v.", "recycling": "n.",
    "red": "adj./n.", "reduce": "v.", "refuse": "v.", "regards": "n.", "relaxing": "adj.",
    "remember": "v.", "repair": "v./n.", "responsibility": "n.", "rubbish": "n.", "rule": "n.",
    "ruler": "n.", "running": "n.", "rush": "v.", "saturday": "n.", "save": "v.",
    "saver": "n.", "school": "n.", "science": "n.", "scientific": "adj.", "scientist": "n.",
    "screen": "n.", "search": "v./n.", "season": "n.", "seat": "n.", "several": "adj.",
    "shape": "n.", "shopping": "n.", "sick": "adj.", "since": "conj./prep.", "sister": "n.",
    "size": "n.", "skate": "v.", "skating": "n.", "skiing": "n.", "skill": "n.",
    "skin": "n.", "sky": "n.", "slim": "adj.", "small": "adj.", "smart": "adj.",
    "smile": "v./n.", "smoke": "n./v.", "snow": "n./v.", "snowy": "adj.", "soldier": "n.",
    "someone": "pron.", "song": "n.", "soon": "adv.", "sort": "n./v.", "sound": "n./v.",
    "south": "n./adj.", "speaker": "n.", "special": "adj.", "spend": "v.", "sport": "n.",
    "sports": "n.", "spring": "n.", "spring roll": "n.", "square": "n.", "stage": "n.",
    "stamp": "n.", "station": "n.", "stay": "v.", "still": "adv.", "store": "n.",
    "straight": "adj./adv.", "student": "n.", "subject": "n.", "succeed": "v.", "successful": "adj.",
    "sugar": "n.", "summer": "n.", "sun": "n.", "sunday": "n.", "sunny": "adj.",
    "supermarket": "n.", "swan": "n.", "swimming": "n.", "symphony": "n.", "t-shirt": "n.",
    "take a bus": "v.phr.", "take turns": "v.phr.", "talent": "n.", "tap": "n./v.", "teacher": "n.",
    "technology": "n.", "telephone": "n.", "television": "n.", "temperature": "n.", "tennis": "n.",
    "than": "conj./prep.", "theatre": "n.", "theory": "n.", "thursday": "n.", "today": "adv./n.",
    "tomorrow": "adv./n.", "tonight": "adv./n.", "tooth": "n.", "tradition": "n.", "traditional": "adj.",
    "traditional chinese medicine": "n.", "transport": "n./v.", "travel": "v./n.", "tree": "n.", "tuesday": "n.",
    "turn left": "v.phr.", "turn right": "v.phr.", "underground": "n./adj.", "understand": "v.", "uniform": "n.",
    "unique": "adj.", "until": "prep./conj.", "vacation": "n.", "video": "n.", "violin": "n.",
    "voice": "n.", "volleyball": "n.", "volunteer": "n./v.", "walking": "n.", "wall": "n.",
    "warm": "adj.", "waste": "v./n.", "wave": "n.", "wealth": "n.", "weather": "n.",
    "wednesday": "n.", "week": "n.", "weekend": "n.", "weigh": "v.", "weight": "n.",
    "wet": "adj.", "white": "adj./n.", "wind": "n.", "window": "n.", "windy": "adj.",
    "winter": "n.", "wise": "adj.", "without": "prep.", "worse": "adj.", "would": "modal v.",
    "year": "n.", "yellow": "adj./n.", "yesterday": "adv./n.",
}

# ==================== 不规则动词变化表 ====================
# 键为动词原形（小写），值为 {"past": 过去式, "pp": 过去分词}
IRREGULAR_VERBS = {
    "break": {"past": "broke", "pp": "broken"},
    "break out": {"past": "broke out", "pp": "broken out"},
    "build": {"past": "built", "pp": "built"},
    "buy": {"past": "bought", "pp": "bought"},
    "catch": {"past": "caught", "pp": "caught"},
    "choose": {"past": "chose", "pp": "chosen"},
    "come": {"past": "came", "pp": "come"},
    "cost": {"past": "cost", "pp": "cost"},
    "cut": {"past": "cut", "pp": "cut"},
    "do": {"past": "did", "pp": "done"},
    "draw": {"past": "drew", "pp": "drawn"},
    "drink": {"past": "drank", "pp": "drunk"},
    "drive": {"past": "drove", "pp": "driven"},
    "eat": {"past": "ate", "pp": "eaten"},
    "fall": {"past": "fell", "pp": "fallen"},
    "feel": {"past": "felt", "pp": "felt"},
    "find": {"past": "found", "pp": "found"},
    "fly": {"past": "flew", "pp": "flown"},
    "forget": {"past": "forgot", "pp": "forgotten"},
    "get": {"past": "got", "pp": "got/gotten"},
    "give": {"past": "gave", "pp": "given"},
    "go": {"past": "went", "pp": "gone"},
    "grow": {"past": "grew", "pp": "grown"},
    "have": {"past": "had", "pp": "had"},
    "hear": {"past": "heard", "pp": "heard"},
    "hit": {"past": "hit", "pp": "hit"},
    "hold": {"past": "held", "pp": "held"},
    "keep": {"past": "kept", "pp": "kept"},
    "know": {"past": "knew", "pp": "known"},
    "leave": {"past": "left", "pp": "left"},
    "lose": {"past": "lost", "pp": "lost"},
    "make": {"past": "made", "pp": "made"},
    "mean": {"past": "meant", "pp": "meant"},
    "meet": {"past": "met", "pp": "met"},
    "pay": {"past": "paid", "pp": "paid"},
    "put": {"past": "put", "pp": "put"},
    "read": {"past": "read", "pp": "read"},
    "ride": {"past": "rode", "pp": "ridden"},
    "run": {"past": "ran", "pp": "run"},
    "say": {"past": "said", "pp": "said"},
    "see": {"past": "saw", "pp": "seen"},
    "sell": {"past": "sold", "pp": "sold"},
    "send": {"past": "sent", "pp": "sent"},
    "sing": {"past": "sang", "pp": "sung"},
    "sit": {"past": "sat", "pp": "sat"},
    "sleep": {"past": "slept", "pp": "slept"},
    "speak": {"past": "spoke", "pp": "spoken"},
    "spend": {"past": "spent", "pp": "spent"},
    "stand": {"past": "stood", "pp": "stood"},
    "swim": {"past": "swam", "pp": "swum"},
    "take": {"past": "took", "pp": "taken"},
    "teach": {"past": "taught", "pp": "taught"},
    "tell": {"past": "told", "pp": "told"},
    "think": {"past": "thought", "pp": "thought"},
    "throw": {"past": "threw", "pp": "thrown"},
    "understand": {"past": "understood", "pp": "understood"},
    "wake": {"past": "woke", "pp": "woken"},
    "wear": {"past": "wore", "pp": "worn"},
    "win": {"past": "won", "pp": "won"},
    "write": {"past": "wrote", "pp": "written"},
    "dream": {"past": "dreamt/dreamed", "pp": "dreamt/dreamed"},
}

# ==================== 补缺例句（针对词库中缺失例句的词汇） ====================
EXTRA_EXAMPLES = {
    "classroom": "Our classroom is big and bright.",
    "blackboard": "The teacher writes new words on the blackboard.",
    "window": "Please open the window to let fresh air in.",
    "door": "Don't forget to close the door when you leave.",
    "floor": "He picked up the book from the floor.",
    "wall": "There is a beautiful picture on the wall.",
    "ceiling": "The lamp on the ceiling gives us light at night.",
    "light": "Turn on the light; the room is too dark.",
    "fan": "It's hot today, so we turn on the electric fan.",
    "computer": "I use the computer to do my homework.",
    "keyboard": "She types very fast on the keyboard.",
    "mouse": "Move the mouse and click on the icon.",
    "screen": "There is a crack on my phone screen.",
    "printer": "Send the file to the printer, please.",
    "telephone": "My grandmother called me on the telephone.",
    "mobile phone": "Don't use your mobile phone in class.",
    "camera": "We took many photos with our new camera.",
    "television": "My family watches the news on television every evening.",
    "radio": "Grandpa listens to the radio every morning.",
    "headphones": "I wear headphones when I listen to music on the bus.",
    "speaker": "The speaker of my computer sounds great.",
    "microphone": "The singer held the microphone and began to sing.",
    "video": "Let me record a short video of the sunset.",
    "movie": "We went to the cinema to see an exciting movie.",
    "music": "Soft music helps me relax after study.",
    "song": "This song is popular among young people.",
    "dance": "They performed a wonderful dance at the party.",
    "game": "Playing chess is my favourite game.",
    "sport": "Swimming is my favourite sport.",
    "football": "The boys are playing football on the playground.",
    "basketball": "Yao Ming is a famous basketball player.",
    "volleyball": "The girls practised volleyball after school.",
    "tennis": "She plays tennis with her father on weekends.",
    "badminton": "We often play badminton in the gym.",
    "swimming": "Swimming in the sea is great fun in summer.",
    "running": "Running every morning keeps me healthy.",
    "walking": "Walking after dinner is good for your health.",
    "cycling": "Cycling to school saves money and keeps you fit.",
    "skating": "The children are skating on the ice happily.",
    "skiing": "My family goes skiing in the mountains every winter.",
    "climbing": "Climbing the mountain took us three hours.",
    "hiking": "We enjoyed hiking in the forest last Sunday.",
    "camping": "They went camping by the lake and lit a fire.",
    "picnic": "We had a picnic in the park last weekend.",
    "travel": "I hope to travel around the world one day.",
    "holiday": "How did you spend your summer holiday?",
    "vacation": "We are going to Beijing during the winter vacation.",
    "weekend": "I usually visit my grandparents at the weekend.",
    "morning": "I get up at six in the morning.",
    "afternoon": "Let's meet at three o'clock this afternoon.",
    "evening": "We do our homework in the evening.",
    "night": "The stars shine brightly at night.",
    "today": "Today is a sunny day.",
    "tomorrow": "We will have a test tomorrow.",
    "yesterday": "It rained heavily yesterday.",
    "week": "There are seven days in a week.",
    "month": "This month has thirty-one days.",
    "year": "She is in her last year of primary school.",
    "season": "Autumn is my favourite season.",
    "spring": "Flowers bloom everywhere in spring.",
    "summer": "We often go swimming in summer.",
    "autumn": "Leaves turn yellow in autumn.",
    "winter": "It often snows here in winter.",
    "weather": "The weather is fine today.",
    "sunny": "It's a sunny day; let's go out to play.",
    "rainy": "Take an umbrella on rainy days.",
    "cloudy": "The sky is cloudy, but it isn't raining.",
    "snowy": "The children love snowy days.",
    "windy": "It is so windy that my hat flew away.",
    "cold": "Put on your coat; it's cold outside.",
    "warm": "The room is warm and comfortable.",
    "hot": "The soup is too hot to drink.",
    "cool": "The breeze feels cool in the evening.",
    "temperature": "The doctor took my temperature first.",
    "degree": "The temperature today is twenty-five degrees.",
    "rain": "The rain stopped and a rainbow appeared.",
    "snow": "The snow lay thick on the ground.",
    "wind": "The wind is blowing hard outside.",
    "cloud": "A dark cloud covered the sun.",
    "sky": "The sky is clear and blue tonight.",
    "apple": "An apple a day keeps the doctor away.",
    "ball": "The cat is playing with a ball of wool.",
    "cat": "The cat is sleeping on the sofa.",
    "dog": "My dog can do some simple tricks.",
    "egg": "I had an egg and some milk for breakfast.",
    "fish": "There are many colourful fish in the river.",
    "girl": "The girl with long hair is my best friend.",
    "hat": "Grandpa wears a straw hat in summer.",
    "ice": "The ice on the lake is thick enough to skate on.",
    "juice": "Would you like a glass of orange juice?",
    "kite": "Let's fly a kite in the park this afternoon.",
    "lion": "The lion is called the king of the forest.",
    "milk": "A glass of milk before bed helps you sleep.",
    "nose": "The elephant has a long nose.",
    "orange": "She peeled an orange and shared it with me.",
    "pen": "May I borrow your pen? Mine is out of ink.",
    "queen": "The queen lives in a beautiful palace.",
    "red": "The red rose is the most beautiful one in the garden.",
    "sun": "The sun rises in the east.",
    "tree": "The children are playing under the big tree.",
    "book": "This book is full of interesting stories.",
    "bag": "My school bag is heavy with books today.",
    "ruler": "Draw a straight line with your ruler.",
    "pencil": "The pencil is too short to use now.",
    "eraser": "Can I use your eraser? I made a mistake.",
    "school": "Our school has a large playground.",
    "teacher": "My English teacher is kind and patient.",
    "student": "Every student in our class works hard.",
    "desk": "There is a lamp on my desk.",
    "chair": "Please sit on this chair.",
    "yellow": "The yellow leaves fall in autumn.",
    "blue": "The sea looks deep blue from the hill.",
    "green": "The fields turn green in spring.",
    "white": "Snow makes the world look white.",
    "black": "The night sky is as black as ink.",
    "father": "My father drives me to school every day.",
    "mother": "My mother cooks delicious meals for us.",
    "brother": "My brother is two years older than me.",
    "sister": "My little sister likes drawing pictures.",
    "friend": "A true friend helps you when you are in trouble.",
    "happy": "The children were happy to see each other again.",
    "good": "Exercise is good for your health.",
    "big": "There is a big shopping mall near my home.",
    "small": "The kitten is very small and lovely.",
    "monday": "We have a class meeting every Monday.",
    "tuesday": "The library is closed on Tuesday afternoon.",
    "wednesday": "We play football after school on Wednesday.",
    "thursday": "There is an English corner every Thursday.",
    "friday": "We are free on Friday evening.",
    "saturday": "I go swimming with my friends every Saturday.",
    "sunday": "The whole family has dinner together on Sunday.",
    "january": "The New Year begins in January.",
    "february": "February is the shortest month of the year.",
    "march": "Trees turn green in March.",
    "april": "April is the best time to fly kites.",
    "sports": "Doing sports makes you strong and healthy.",
    "reading": "Reading before bed is a good habit.",
    "shopping": "Mom does the shopping on Saturdays.",
    "cooking": "Cooking is an important life skill.",
    "hospital": "The doctor works in a famous hospital.",
    "library": "You must keep quiet in the library.",
    "supermarket": "We buy fruit at the supermarket near our home.",
    "turn left": "Turn left at the second crossing and you will see the bank.",
    "turn right": "Turn right at the corner to get to the bus stop.",
    "go straight": "Go straight on and the station is in front of you.",
    "take a bus": "You can take a bus to the city centre.",
    "by subway": "It takes only ten minutes by subway.",
    "family": "There are four people in my family.",
    "subject": "Which subject do you like best?",
    "favorite": "Blue is my favorite color.",
    "breakfast": "A good breakfast gives you energy for the morning.",
    "lunch": "We have lunch at school at noon.",
    "dinner": "The whole family enjoys dinner together every evening.",
    "bedroom": "My bedroom is small but tidy.",
    "living room": "The family watches TV in the living room.",
    "kitchen": "Mom is cooking in the kitchen.",
    "bathroom": "He is taking a shower in the bathroom.",
    "interesting": "This is an interesting story book.",
    "difficult": "Nothing is difficult if you put your heart into it.",
    "easy": "The question is easy enough for a child to answer.",
    "boring": "The lecture was so boring that some students fell asleep.",
    "exciting": "The football match was really exciting.",
    "relaxing": "Listening to music is relaxing after a busy day.",
    "dangerous": "It is dangerous to swim in this river.",
    "practice": "Practice makes perfect.",
    "remember": "Please remember to bring your homework tomorrow.",
    "forget": "Don't forget to turn off the lights.",
    "understand": "I can't understand this sentence. Can you explain it?",
    "explain": "The teacher explained the grammar clearly.",
    "science": "We did an interesting experiment in science class.",
    "history": "I am interested in the history of ancient China.",
    "geography": "We learn about different countries in geography.",
    "biology": "Biology teaches us how living things grow.",
    "achieve": "You will achieve your dream through hard work.",
    "attitude": "A positive attitude leads to success.",
    "challenge": "Learning a foreign language is a big challenge.",
    "confidence": "She answered the question with confidence.",
    "creativity": "Children's creativity should be encouraged.",
    "develop": "Reading develops the mind.",
    "education": "Education plays an important role in our life.",
    "encourage": "Parents should encourage children to try new things.",
    "environment": "We must protect the environment for future generations.",
    "experience": "Travelling gives us valuable experience.",
    "government": "The government built a new school in the village.",
    "imagination": "A good writer needs a rich imagination.",
    "improve": "Practising every day will improve your English.",
    "influence": "Teachers have a great influence on their students.",
    "knowledge": "Knowledge is power.",
    "opportunity": "Don't miss this good opportunity to study abroad.",
    "pollution": "Air pollution is a serious problem in big cities.",
    "population": "The population of this city is over ten million.",
    "protect": "We should protect wild animals.",
    "recycling": "Recycling paper and plastic saves resources.",
    "responsibility": "It is our responsibility to keep the classroom clean.",
    "scientific": "The answer must be based on scientific research.",
    "succeed": "Work hard, and you will succeed.",
    "technology": "Science and technology change our lives.",
    "volunteer": "She works as a volunteer at the old people's home.",
    "abandon": "Never abandon your dreams, no matter how hard it is.",
    "absence": "His absence from school was because of illness.",
    "accomplish": "She worked hard to accomplish the task ahead of time.",
    "accurate": "His answer is accurate to the last digit.",
    "adequate": "Make sure you get adequate sleep before the exam.",
    "admire": "I admire her courage to speak in public.",
    "adventure": "Climbing the mountain was a real adventure.",
    "afford": "We can't afford such an expensive car.",
    "aggressive": "An aggressive attitude won't win you friends.",
    "ambition": "His ambition is to become a scientist.",
    "analyze": "Scientists analyze the data carefully.",
    "anxiety": "She felt great anxiety before the exam results came out.",
    "appreciate": "I really appreciate your help.",
    "appropriate": "Please wear appropriate clothes for the ceremony.",
    "approximately": "The journey takes approximately two hours.",
    "argument": "They had an argument about where to go.",
    "artificial": "This flower is made of artificial silk.",
    "authority": "He is an authority on ancient history.",
    "average": "The average temperature here is 25 degrees.",
    "barely": "I could barely hear the sound.",
    "beneficial": "Eating vegetables is beneficial to your health.",
    "capability": "This machine has the capability to work day and night.",
    "circumstances": "Under no circumstances should you give up.",
    "civilization": "Ancient China had a splendid civilization.",
    "colleague": "My colleagues are friendly and helpful.",
    "commit": "He committed himself to protecting the environment.",
    "communicate": "We communicate with each other by email.",
    "consequence": "Every choice has its consequence.",
    "considerable": "The project needs considerable time and money.",
    "contribute": "Everyone should contribute to building a better school.",
}


# 合并教材不规则动词表（上海教育出版社 7A/8A 附录，约107词）
try:
    from wordbank_shcep import TEXTBOOK_IRREGULAR
    for _base, _forms in TEXTBOOK_IRREGULAR.items():
        if _base not in IRREGULAR_VERBS:
            IRREGULAR_VERBS[_base] = _forms
except ImportError:
    pass


def enrich_word(w: dict) -> bool:
    """为单个词条补充词性、不规则动词变化、缺失例句
    返回是否有修改"""
    changed = False
    key = w.get("word", "").strip().lower()
    if not w.get("pos") and key in POS_MAP:
        w["pos"] = POS_MAP[key]
        changed = True
    if not w.get("example_sentence") and key in EXTRA_EXAMPLES:
        w["example_sentence"] = EXTRA_EXAMPLES[key]
        changed = True
    if key in IRREGULAR_VERBS and not w.get("irregular_forms"):
        w["irregular_forms"] = IRREGULAR_VERBS[key]
        changed = True
    return changed


def get_word_extra(word: str) -> dict:
    """按单词文本动态查询词性和不规则变化（不依赖数据库，用于复习题等场景）"""
    key = (word or "").strip().lower()
    return {
        "pos": POS_MAP.get(key),
        "irregular_forms": IRREGULAR_VERBS.get(key),
    }
